### PR TITLE
Expose indexer opts

### PR DESCRIPTION
**Pull request by ManyTheFish**
# Pull Request

Expose indexer options in order to manage the consumed memory and threads during indexing.

`--max-memory` (env: `MEILI_MAX_MEMORY`): Humanized maximum memory used by the indexer.
`--indexing-jobs` (env: `MEILI_INDEXING_JOBS`): number of threads used by the indexer.

### CODE REVIEW

**Comment by gmourier** [comment]
Thanks, @ManyTheFish 💪, we might decide to explain that in the documentation, it will go through a specification for each newly exposed env var and CLI option anyway.

We may want to keep by default the values that we have chosen at the engine level and to replace it with the user values as soon as they are filled in. What do you think about it?

**Comment by ManyTheFish** [comment]
@gmourier, this draft PR is not meant to be merged for now; I want to know if it fits the need of the  @meilisearch/saas-team before. 🤓
The default behavior is not changed, these new options will override it. 🙂

**Comment by curquiza** [comment]
bors try

**Comment by curquiza** [comment]
Closing this since v0.27.0 is out!

**Pull request closed without merging**
