### PR TITLE
Improves clarity of the code that receives payloads

### PR DESCRIPTION
**Pull request by Kerollmops**
This PR makes small changes to #3164. It improves the clarity and simplicity of some parts of the code.

### CODE REVIEW

**Review by irevoire — DISMISSED** [review]

**Review by Kerollmops — COMMENTED** [review]
bors merge

**Review by irevoire — APPROVED** [review]

**Comment by Kerollmops** [comment]
Sorry @irevoire, but I needed to reintroduce the parsing of either an array or an object when the `array_each` function fails because we lost a cool error message...

**Review by irevoire — APPROVED** [review]
Oooh yeah right I remember this error message

**Review by Kerollmops — COMMENTED** [review]
bors merge

**Pull request merged**
