### PR TITLE
Contributor guidelines

### PR DESCRIPTION
**Pull request by erlend-sh**
Preliminary contributor guidelines, heavily based on the [Vector doc](https://github.com/timberio/vector/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by erlend-sh** [comment]
- Do we we want to follow www.conventionalcommits.org?

- We we want a Review guide? https://github.com/timberio/vector/blob/master/REVIEWING.md

- Need CI instructions

- Need tests instructions

- Need profiling instructions, although that can probably wait for a later iteartion.

**Comment by Kerollmops** [comment]
- I would prefer we follow this commit convention https://chris.beams.io/posts/git-commit/.
- I am not sure we need a code review guide that complex, but something that helps the reviewer now if the changelog must be updated can be good for the moment, this would help the integration/doc teams.
- We can just explain that we use Github Actions and look into the `.github` folder if they want to more or even ask us questions.
- For the tests suite we follow the classic `cargo test` way with a little tuning: we run them with release optimizations and [should make this the default in the Cargo.toml](https://github.com/rust-lang/cargo/issues/691).

**Review by Kerollmops — APPROVED** [review]

**Pull request merged**
