### PR TITLE
WIP: Auto-generate embeddings for documents and queries

### PR DESCRIPTION
**Pull request by dureuill**
This PR adds support for generating embeddings for documents and queries

# How to use

- As a quirk of the current implementation, have the field `"_vectors": null` in at least one of the documents of your dataset.
- Run the indexing like normal
- To perform vector search requests with auto-generation of the embeddings for the query, use the `vector` field of the request, but pass it the string value of your query.

Example: `{ "vector": "batman" }`

# TODO

- [x] Decide on model provisioning strategy
- [x] Allow configuring model
- [ ] In search response, reinstate similarity computation and display vector that was computed
- [x] Decide sane defaults
- [x] Conditionally enable autoembedding depending on settings
- [x] no longer require `"_vectors": null"

### CODE REVIEW

**Comment by hdytsgt** [comment]
Hi @dureuill!

The auto-generated embedding looks really promising! 

I was wondering about your planning on how the model will be attached to an index? Will all indexes using the same model or an index may have a different model than the other?

Assuming we have two indexes so we can perform image similarity search and text search : 
1. Index for storing movies poster/image embedding using `openai/clip-vit-base-patch32`
2. Index for storing movies metadata embedding in multilingual using `sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2`

Will that be possible? Thank you!

Hats off to your work!

**Comment by dureuill** [comment]
hi @hdytsgt :wave:

Thanks for the encouraging message ❤️ 

> I was wondering about your planning on how the model will be attached to an index? Will all indexes using the same model or an index may have a different model than the other?


A single index may use multiple models. Different indexes may use different models.

> Assuming we have two indexes so we can perform image similarity search and text search :

Note that for the upcoming v1.6, we're only supporting the auto embedding of text via BERT models, no image similarity. You will be able to do image similarity by providing the embeddings yourself, like previously.

It would look like this:

1. Enable the experimental vector store feature:
```
 curl \
  -X PATCH 'http://localhost:7700/experimental-features/' \
  -H 'Content-Type: application/json' -H 'Authorization: Bearer foo' \
--data-binary '{ "vectorStore": true
  }'
```
2. Setup the embedders for your index of interest by sending the settings for your index:
```json
{
  "embedders": {
    "default": {
      "source": { "huggingFace": {}},
      "documentTemplate": {
        "template": "A movie titled '{{doc.title}}' whose description starts with {{doc.overview|truncatewords: 20}}"
      }
    },
    "image": {
      "source": { "userProvided": { "dimensions": 512 } }
    },
    "translation": {
      "source": { "huggingFace": {
        "model": "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
      }},
      "documentTemplate": {
        "template": "A movie titled '{{doc.title}}' whose description starts with {{doc.overview|truncatewords: 20}}"
      }
    }
  }
}
```
3. You then add some documents:
```json
[{"id":9607,"title":"Super Mario Bros.","overview":"Mario and Luigi, plumbers from Brooklyn, find themselves in an alternate universe where evolved dinosaurs live in hi-tech squalor. They're the only hope to save our universe from invasion by the dino dictator, Koopa.","genres":["Science Fiction","Adventure","Comedy","Family"],"poster":"https://image.tmdb.org/t/p/w500/lE8KFoPErukKBRTy9De25ClpxH9.jpg","release_date":738547200,
"_vectors": {
  "image":  // need to specify the embedding of correct dimension for the `image` category
[0.0,
 0.0,
 ...,
 0.0,
 0.0]
}
// no need to specify for the `default` and `translation` embedders, the embedding will be computed automatically
},
{"id":9323,"title":"Ghost in the Shell","overview":"In the year 2029, the barriers of our world have been broken down by the net and by cybernetics, but this brings new vulnerability to humans in the form of brain-hacking. When a highly-wanted hacker known as 'The Puppetmaster' begins involving them in politics, Section 9, a group of cybernetically enhanced cops, are called in to investigate and stop the Puppetmaster.","genres":["Action","Animation","Science Fiction"],"poster":"https://image.tmdb.org/t/p/w500/9gC88zYUBARRSThcG93MvW14sqx.jpg","release_date":816652800,
"_vectors": { "image":
[0.0,
 0.0,
 ...,
 0.0,
 0.0]
}}]
```
4. Lastly, you can do a search:
```json
{ 
  "q": "Plumbers and dinosaurs",  // will be embedded by the default embedder
  "limit": 20, 
  "hybrid": {
    "semanticRatio": 1.0 // do a full vector search
  }  
}
```

to get a translation and benefit from the multi lingual capabilities of the `paraphrase-multilingual-MiniLM-L12-v2` model, you would specify the embedder:

```json
{ 
  "q": "Le film avec les plombiers et les dinosaures",  // will be embedded by the "translation" embedder
  "limit": 20, 
  "hybrid": {
    "semanticRatio": 1.0,  // do a full vector search
    "embedder": "translation" // provide embedder name here
  }  
}
```

lastly, to do an image similarity search, you will need to pass the embedding yourself:
```json
{ 
  "vector": [0.0, ..., 0.0],  // provided by you
  "limit": 20, 
  "hybrid": {
    "semanticRatio": 1.0,  // do a full vector search
    "embedder": "image", // compare with the "image" embeddings from the index
  }  
}
```

We are interested in adding image embedding eventually, but this poses some design questions (we are handling text so far in Meilisearch) and won't make the cut for v1.6

> Hats off to your work!

Thank you 😊  I'm racing to finish the work for v1.6-RC.0 that's planned next week!

**Comment by hdytsgt** [comment]
Oh wow! Searching while defining which model to use is actually pretty cool and handy! 🎉

Hopefully that doesn't affect the performance too, considering loading the uncached model is relatively slow.

Thank you for the detailed explanation, can't wait to try v1.6.

Awesome work @dureuill!

**Comment by dureuill** [comment]
Superseded by #4226

**Pull request closed without merging**
