### PR TITLE
Make sure the index scheduler never stops running

### PR DESCRIPTION
**Pull request by irevoire**
# Pull Request

## Related issue
Fixes https://github.com/meilisearch/meilisearch/issues/4748

## What does this PR do?
- Whatever happens, we always try to process tasks once every minute (if no tasks are enqueued that's practically free)

### CODE REVIEW

**Comment by irevoire** [comment]
bors merge

**Comment by michalkorzawski** [comment]
@irevoire, any way this fix can be in v1.10.0 ?

**Comment by curquiza** [comment]
Hello @michalkorzawski 
@irevoire and @dureuill are on Holidays currently. But I guess if they decided to merge this in v1.11 and not v1.10, it's probably about the risk that could bring the fix.

v1.10 is released next Monday. I'll let them answer when they come back next week and if v1.10.1 is needed for this

**Comment by michalkorzawski** [comment]
thanks!

**Comment by dureuill** [comment]
hey @michalkorzawski 

We'll be releasing a v1.10.1 containing unrelated fixes next week, so we took the opportunity to grab the fix from `main` as well :rocket:

**Comment by michalkorzawski** [comment]
hey @dureuill, that's awesome! Thank you very much

**Pull request merged**
