### PR TITLE
 Add a documentTemplateMaxBytes parameter to limit the max length of document templates

### LINKED ISSUE #4885: Add a `documentTemplateMaxBytes` parameter to limit the max length of document templates
See [public usage](https://meilisearch.notion.site/v1-11-AI-search-changes-0e37727193884a70999f254fa953ce6e#a3d63628129e40adba943ae7b8ec06c2)

### PR DESCRIPTION
**Pull request by dureuill**
# Pull Request

## Related issue
Fixes #4885 

See [public usage](https://meilisearch.notion.site/v1-11-AI-search-changes-0e37727193884a70999f254fa953ce6e#a3d63628129e40adba943ae7b8ec06c2)

### CODE REVIEW

**Review by ManyTheFish — APPROVED** [review]
It their is no needs to modify analytics, LGTM :)

**Comment by dureuill** [comment]
@ManyTheFish 

Added analytics, and also we no longer reindex when decreasing the max bytes value.

**Review by ManyTheFish — APPROVED** [review]

**Comment by dureuill** [comment]
bors merge

**Comment by dureuill** [comment]
Rebased

**Review by ManyTheFish — APPROVED** [review]
bors merge

**Pull request merged**
