### PR TITLE
Use milli reexported tokenizer 

### LINKED ISSUE #1888: Improve Hangul tokenization
Steps:
- [x] Merge https://github.com/meilisearch/tokenizer/pull/60 (thanks @datamaker 🎉)
- [x] Release the [tokenizer](https://github.com/meilisearch/tokenizer) -> [v0.2.6](https://github.com/meilisearch/tokenizer/releases/tag/v0.2.6) is out
- [x] Update the tokenizer dependency in [milli](https://github.com/meilisearch/milli)
- [ ] Release milli
- [ ] Update milli dependency in this repo (MeiliSearch)
- [ ] Use milli tokenizer instead of importing crate

### PR DESCRIPTION
**Pull request by ManyTheFish**
Use milli reexported tokenizer instead of importing meilisearch-tokenizer dependency.

fix #1888

### CODE REVIEW

**Comment by ManyTheFish** [comment]
bors merge

**Comment by ManyTheFish** [comment]
bors merge

**Review by MarinPostma — APPROVED** [review]

**Comment by curquiza** [comment]
bors merge-

**Comment by curquiza** [comment]
bors merge

**Pull request merged**
