### PR TITLE
Inferring whether to show or Hide API Key box

### PR DESCRIPTION
**Pull request by sanders41**
Relates to #1261

This is one potential solution for inferring whether an instance has an API key and show or hide the text input box accordingly. When the page first loads a request is sent to the server with no API key. If that request was successful then no API key is need so the box is hidden. If the request returns with a 401 status then the API Key was needed and it is shown.

### CODE REVIEW

**Comment by curquiza** [comment]
Without any master key defined:
Capture d’écran 2021-02-25 à 18 57 55

With a master key defined:
Capture d’écran 2021-02-25 à 18 58 43

It's a really good idea from my POV 🚀  @react-learner is it ok for you?

**Comment by curquiza** [comment]
Thanks @sanders41, it's nice to see you everywhere 😄

**Review by react-learner — APPROVED** [review]
Awesome work! You spoil us @sanders41 ! 😁🔥

**Review by curquiza — APPROVED** [review]
bors merge

**Pull request merged**
