### PR TITLE
Update mini-dashboard to v0.2.5

### PR DESCRIPTION
**Pull request by mdubus**

### CODE REVIEW

**Review by curquiza — CHANGES_REQUESTED** [review]
I don't see the version of Meilisearch, is it expected?

Capture d’écran 2023-01-10 à 17 19 56

**Comment by mdubus** [comment]
> I don't see the version of Meilisearch, is it expected?
> 
> Capture d’écran 2023-01-10 à 17 19 56

That's weird because I tested locally and I do have the Meilisearch version: 
Capture d’écran 2023-01-11 à 08 08 56

Plus, on your screen you have the old Meilisearch logo 🤔

Can you double check before I do some more investigation? 🙏

**Comment by curquiza** [comment]
Oh you are right for the meilisearch logo, I didn't even notice 😂 

I mean the version at the top left, I should see `v1.0.0`

**Review by curquiza — APPROVED** [review]
Of course (and hopefully!) it was an issue on my side!

Good to me, thanks a lot momo

**Comment by curquiza** [comment]
bors merge

**Pull request merged**
