### PR TITLE
DigitalOcean marketplace button

### PR DESCRIPTION
**Pull request by erlend-sh**

### CODE REVIEW

**Comment by curquiza** [comment]
@erlend-sh, you let 2 `.DS_Store` files 🙂

**Comment by erlend-sh** [comment]
Woops! Good now?

**Comment by Kerollmops** [comment]
Hum, that nearly that @erlend-sh, you should rebase on master now, you are out-of-date.

**Comment by erlend-sh** [comment]
Things got messy! New attempt in #678

**Pull request closed without merging**
