### PR TITLE
Add the specific routes for the pagination and faceting settings

### LINKED ISSUE #2522: v0.28 RC: cannot access to `pagination` and `faceting` settings via the settings sub routes
Sorry if I missed something.
Version: v0.28.0rc0

When I get the settings using `GET /indexes/:uid/settings` I can see the `pagination` and `faceting` being present. I can even update them using `GET /indexes/:uid/settings`.

However I cannot get/update/reset them using the following endpoints
- `/indexes/:uid/settings/pagination`
- `/indexes/:uid/settings/faceting`

I get a `404`, these endpoints seem not to exist.

### PR DESCRIPTION
**Pull request by Kerollmops**
Fixes #2522

### CODE REVIEW

**Review by MarinPostma — APPROVED** [review]
👍

bors merge

**Comment by Kerollmops** [comment]
Oups, please wait a minute, I try to add more tests 😄

**Comment by Kerollmops** [comment]
We are ready now, you can review @MarinPostma

**Review by MarinPostma — APPROVED** [review]

**Review by curquiza — APPROVED** [review]
thanks!

bors merge

**Pull request merged**
