### PR TITLE
Sort displayedAttributes field

### LINKED ISSUE #943: Sort fields without consistency in lexicographical order
# Summary

Some fields like:
- `displayedAttributes` in `GET /index/:uid:/settings` and `GET /index/:uid:/settings/displayed-attributes` routes
- `facetsDistribution`  in a search query `/indexes/test/search?facetsDistribution=%5B%22color%22%5D`

are never consitently sorted between same requests.

# Motivations

Same request should respond same results in the same order.

# Implementation

`displayedAttributes` and `facetsDistribution` use the `HashSet` struct which is an unsorted structure, a fast fix should be to sort fields in meilisearch-http  before returning them.

# Related

related to #890 

- [ ] Validated by the team
- [ ] Test added

### PR DESCRIPTION
**Pull request by gorogoroumaru**
Fix #943

displayedAttributes use the HashSet struct which is an unsorted structure, so I changed the implementation from HashSet into BTreeSet.

### CODE REVIEW

**Comment by Kerollmops** [comment]
Hey @gorogoroumaru,

Is there something wrong with this PR? Do you want some help? Could you tell us why you closed this PR?

Thank you very much :)

**Comment by gorogoroumaru** [comment]
Thank you @Kerollmops, and I’m sorry for suddenly closing this PR.
I managed to sort displayedAttributes fields and I was trying to sort facetsDistribution as described in the issue943.
I read the document about facetsDistribution.
However I couldn’t understand how to use it and how to sort it.

**Comment by gorogoroumaru** [comment]
@LegendreM, thank you very much!
I will work on this issue again.

**Comment by LegendreM** [comment]
Hey @gorogoroumaru congratulation for your Pull Request, we should change the test to check the new behaviors of the engine 🔍.

In [meilisearch-http/tests/settings.rs](https://github.com/gorogoroumaru/MeiliSearch/blob/f4d918d22aee742fb2deb0bc89afb0fbec4337b5/meilisearch-http/tests/settings.rs#L86) we are currently testing equality using a param `ordered: false` which ignore order in json array:
```rust
    assert_json_eq!(expect, response, ordered: false);
```

Copy pasting [this part](https://github.com/gorogoroumaru/MeiliSearch/blob/f4d918d22aee742fb2deb0bc89afb0fbec4337b5/meilisearch-http/tests/settings.rs#L6-L59) to create a new test to check equality using `ordered: true`  should be good for settings.

For `stats` we'll have to create our test from scratch in [meilisearch-http/tests/index.rs](https://github.com/gorogoroumaru/MeiliSearch/blob/issue943/meilisearch-http/tests/index.rs)

using:
```rust
let mut server = common::Server::test_server().await;
```
> create a server with default settings and some documents

```rust
let (response, status_code) = server.get_index_stats();
```
> call `/stats` route

```rust
assert_json_eq!(expected, response, ordered: true);
```
> compare 2 json and check if the arrays are sorted in same order

I'll merge this PR when the feature is tested 🙂

If something is not well explained, don't hesitate to ask!

**Comment by gorogoroumaru** [comment]
Thank you @LegendreM!
I changed the test as requested!

**Review by MarinPostma — APPROVED** [review]
Thank for your contribution, this is nicely done :+1: 
bors r+

**Comment by MarinPostma** [comment]
bors merge

**Comment by LegendreM** [comment]
Hello @gorogoroumaru thank you for your contribution! We would like to send you the contributor's sticker 2020,
can you make your email public on github or followback [meilisearch] (https://twitter.com/meilisearch) and send your email as a private message?

Thanks!

**Comment by gorogoroumaru** [comment]
Thank you @LegendreM for your support!
I made my email address public.

**Pull request merged**
