### PR TITLE
Support boolean for the no-analytics flag

### LINKED ISSUE #1983: Disable analytics option has wrong behavior
**Describe the bug**

Following the [documentation](https://docs.meilisearch.com/reference/features/configuration.html#disable-analytics), we should be able to disable/enable the built-in telemetry by setting `--no-analytics` or `MEILI_NO_ANALYTICS` to `true`/`false`.

This is not the current behavior of `MeiliSearch`, which is :
- If the variable is set (to anything), `MeiliSearch` built-in telemetry is disabled
- If the variable is not used, `MeiliSearch` built-in telemetry is enabled

**To Reproduce**

```bash
~ MEILI_NO_ANALYTICS=true ./meilisearch-0.24.0 -> Analytics OFF
~ MEILI_NO_ANALYTICS=false ./meilisearch-0.24.0 -> Analytics OFF
~ MEILI_NO_ANALYTICS="" ./meilisearch-0.24.0 -> Analytics OFF
~ ./meilisearch-0.24.0 --no-analytics true -> Analytics OFF
~ ./meilisearch-0.24.0 --no-analytics false -> Analytics OFF
~ ./meilisearch-0.24.0 --no-analytics "" -> Analytics OFF

~ ./meilisearch-0.24.0 -> Analytics ON
```

**Expected behavior**
```bash
~ MEILI_NO_ANALYTICS=false ./meilisearch-0.24.0 -> Analytics ON
~ ./meilisearch-0.24.0 --no-analytics false -> Analytics ON
```

OR Documentation update. @meilisearch/docs-team 

**MeiliSearch version:** 

`v0.24.0`, `v0.23.1`

### PR DESCRIPTION
**Pull request by Kerollmops**
This PR fixes an issue with the `no-analytics` flag that was ignoring the value passed to it, therefore a `no-analytics false` was just understood as a `no-analytics` and was effectively disabling the analytics instead of enabling them. I found [a closed issue about this exact behavior on the structopt repository](https://github.com/TeXitoi/structopt/issues/468) and applied it here.

I don't think we should update the documentation as it must have worked like this from the start of this project. I tested it on my machine and it is working great now. Thank you @nicolasvienot for this issue report.

Fixes #1983.

### CODE REVIEW

**Comment by curquiza** [comment]
@guimachiavelli, I remembered we talked about this problem some weeks ago, it will be fixed in v0.25.0.
It does not impact the docs as far as I know since the previous buggy behavior was not described in the docs.

**Review by curquiza — APPROVED** [review]
it works on my side! 💪

**Comment by Kerollmops** [comment]
@curquiza Even by using the environment variable `MEILI_NO_ANALYTICS`?

**Comment by curquiza** [comment]
Yes, I also tested with it, I get an error message when trying with `MEILI_NO_ANALYTICS=lol`. Is it what you expected?

**Comment by Kerollmops** [comment]
Then we can...
bors merge

**Pull request merged**
