### PR TITLE
upgrade actix-web to v3

### PR DESCRIPTION
**Pull request by robjtede**
Test failures are the same before and after upgrade.

### CODE REVIEW

**Comment by qdequele** [comment]
Thank you very much @robjtede! We will see how we can merge that soon.

**Review by MarinPostma — APPROVED** [review]

**Comment by Kerollmops** [comment]
Hey @robjtede,

Thank you very much, could you please just `cargo update` to update the `Cargo.lock` as there already was a patch 3.0.2 ?

**Comment by Kerollmops** [comment]
Thank you very much!

bors try

**Review by Kerollmops — APPROVED** [review]

**Pull request merged**
