### PR TITLE
Post search route

### PR DESCRIPTION
**Pull request by MarinPostma**
create a post route for search queries, to prevent preflight queries due to the presence of a x-meili-api-key in the header.

thanks to @jiminy-billy-bob for pointing this out in #727 

bellow is a graph of the improvement in search time when using an API key thanks to this:
image

zones where the 2 are equal is when backspacing in the query bar and the browser rely on cache. Y-coordinates in ms

https://github.com/MarinPostma/meilisearch-network-bench

### CODE REVIEW

**Comment by jiminy-billy-bob** [comment]
Just to make sure I understand:

- Using a POST request instead of GET prevents the browser from sending a preflight request?
- Or now we need to send the API Key as part of the POST request body instead of a header?

**Comment by MarinPostma** [comment]
so the trick is you can set a TTL for the preflight check (eg 10 min for chrome and 24h for firefox) as long as the url remain the same. This is the case for post but not for get, so we can keep authentication in the header and cache the OPTION request for some time when using POST

**Comment by jiminy-billy-bob** [comment]
Interesting! So there will be an OPTION request sent out only every 10 minutes? That sounds reasonable.

**Comment by MarinPostma** [comment]
yes :)

**Comment by Kerollmops** [comment]
Don't forget to create a PR to the documentation repository to add this to the doc, please link this PR in the one on the doc.

**Pull request merged**
