### PR TITLE
add functionnal + error tests on the swap_indexes route and fix a confusing error message

### PR DESCRIPTION
**Pull request by irevoire**
Fix https://github.com/meilisearch/meilisearch/issues/3340
Fix part of https://github.com/meilisearch/meilisearch/issues/3325
Fix https://github.com/meilisearch/meilisearch/issues/3381

Test both the functionality and the error codes

### CODE REVIEW

**Comment by loiclec** [comment]
Note: I rebased this branch on top of release-v1.0.0 and updated the result of the snapshot tests

**Comment by curquiza** [comment]
@irevoire you linked the current PR, not the issue in the PR description

**Comment by irevoire** [comment]
Hey @loiclec, yeah I'll do that here instead of pushing broken tests :grin:

**Review by loiclec — APPROVED** [review]
nice!

**Comment by loiclec** [comment]
bors merge

**Pull request merged**
