### PR TITLE
Revert "Stream documents" and keep heed+arroy to the latest verion

### PR DESCRIPTION
**Pull request by irevoire**
Reverts meilisearch/meilisearch#4544

Fixes https://github.com/meilisearch/meilisearch/issues/4641

I didn’t realize that some http clients were not handling chunked http requests like you would expect (if you ask the body, it gives you the body), which made the previous PR breaking.

There is no way to provide a good fix to the issue we initially wanted to fix without breaking meilisearch and that’s not planned for now.

### CODE REVIEW

**Review by Kerollmops — APPROVED** [review]
Thank you very much for the investigation and different integration tests. It was, in fact, quite hard to know that it would be breaking in advance.
bors merge

**Comment by curquiza** [comment]
bors merge

**Comment by irevoire** [comment]
bors merge

**Comment by curquiza** [comment]
bors merge

**Comment by Kerollmops** [comment]
Bors merge

**Pull request merged**
