### PR TITLE
change the wording of Amplify to make it clearer

### PR DESCRIPTION
**Pull request by fharper**

### CODE REVIEW

**Comment by qdequele** [comment]
The result will be `Anonymous telemetry on: Enable`, is it what you expected?

**Comment by fharper** [comment]
@qdequele : yes

**Comment by curquiza** [comment]
Hello @fharper!
Maybe we are wrong, but `Anonymous telemetry on: Enable` seems weird to us. Maybe `Anonymous telemetry: Enable` would be better?

**Comment by fharper** [comment]
> Hello @fharper!
> Maybe we are wrong, but `Anonymous telemetry on: Enable` seems weird to us. Maybe `Anonymous telemetry: Enabled` would be better?

Oh, yes, not sure why I put the on or didn't remove it

**Comment by fharper** [comment]
I updated, you can squash it

**Review by curquiza — APPROVED** [review]
thanks!

bors merge

**Pull request merged**
