### PR TITLE
Fix auth error

### PR DESCRIPTION
**Pull request by MarinPostma**
fix a small auth error, that set the invalid token error token to "hello". This was invilisble to the user because the invalid token is not returned.

thank you hawk-eye @irevoire

### CODE REVIEW

**Review by irevoire — DISMISSED** [review]
Yeas! :eagle: 
bors merge

**Comment by irevoire** [comment]
bors cancel

**Comment by curquiza** [comment]
Sould be merged into `release-v0.23.0`

**Review by irevoire — APPROVED** [review]
bors merge :eagle:

**Pull request merged**
