### PR TITLE
bors setup

### PR DESCRIPTION
**Pull request by MarinPostma**
set up bors to run the tests and merge automatically.

the tests are now run only on staging and trying branches

you can use `bors r+` to test and merge the branch into master if the tests succeed

or

you can just use `bors try` to run the test on the trying branch (synced with master)

### CODE REVIEW

**Comment by MarinPostma** [comment]
bors try

**Comment by MarinPostma** [comment]
bors try

**Comment by LegendreM** [comment]
Hello @MarinPostma 👋 ,
As you explained me the bors job will aggregate several PR in a `staging` branch. In this case, passing test only on `staging` branch could be harder for contributors to  interpret test results, no ? 🤔

**Comment by MarinPostma** [comment]
Hey @LegendreM bors run test in batches, in case the test fails it bisects the branch to find the faulty pr

**Comment by MarinPostma** [comment]
bors try

**Comment by MarinPostma** [comment]
bors try

**Pull request merged**
