### PR TITLE
Integrate the new indexer

### PR DESCRIPTION
**Pull request by curquiza**
For those wanting to test the new indexer. This is a WIP!

```bash
git clone git@github.com:meilisearch/MeiliSearch.git
cd MeiliSearch
git checkout test-new-indexer
cargo run --release -- --master-key=YourMasterKey
```

If it does not work, check `rustup` is up to date

```bash
rustup update
```

### CODE REVIEW

**Comment by Kerollmops** [comment]
Hey @bb, you can try out this branch if you want, it should have most of the fixes you requested about the facets 🦄

**Comment by bb** [comment]
@Kerollmops thank you! From what I can see, the faceting stuff seems fine ✅ .

However, the indexing issue remains: https://github.com/meilisearch/MeiliSearch/issues/1590#issuecomment-900655628

**Review by Kerollmops — APPROVED** [review]
LGTM as I am the author of some commits 🤣
bors merge

**Comment by Kerollmops** [comment]
bors merge

**Comment by curquiza** [comment]
Bors merge

**Comment by Kerollmops** [comment]
bors merge

**Comment by curquiza** [comment]
Seems like tests do not work on Windows

**Comment by curquiza** [comment]
I merge this despite the error on Windows so that we can do the RC and the integration team can start their work. This issue should be fixed in the next RC version

**Pull request merged**
