### PR TITLE
Make milli use edition 2021

### LINKED ISSUE #4635: Make milli use edition 2021
It would be better to use the latest edition everywhere.

### PR DESCRIPTION
**Pull request by hanbings**
# Pull Request

## Related issue
Fixes #4635

## What does this PR do?
- Run `cargo fix --edition`
- Changed edition 2018 to 2021 in `milli/Cargo.toml`.

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Comment by Kerollmops** [comment]
Hey, @hanbings 👋 Thank you very much, but could you also run `cargo fix --edition-idioms` and fix the many issues shown (mostly `Xxx<'_>`)?

**Review by Kerollmops — CHANGES_REQUESTED** [review]
Hey, @hanbings 👋 Thank you very much, but could you also run `cargo fix --edition-idioms` and fix the many issues shown (mostly `Xxx<'_>`)?

**Comment by hanbings** [comment]
Thanks. I've run `cargo fix --edition-idioms` on new commits and annotated that as much as possible. :)

**Comment by curquiza** [comment]
bors try

**Comment by curquiza** [comment]
@hanbings thanks for your PR

Looks like our CI is failing now on ubuntu tests.

**Comment by hanbings** [comment]
I checked the error in CI, and it didn't seem to be related to the millisearch code. Then I retrieved some information from the search engine: https://github.com/actions/checkout/issues/1590. I guess maybe there is something wrong with the `checkout` plugin in Github Action.

**Comment by Kerollmops** [comment]
Hey @hanbings 👋  Great news! We fixed the CI 🎉  Could you rebase on main, please?

**Comment by Kerollmops** [comment]
bors try

**Review by Kerollmops — APPROVED** [review]
In fact... we can merge. Bors rebases before merging so no need to do anything.
Thank you very much @hanbings, nice work 🙏

bors merge

**Comment by hanbings** [comment]
> bors merge

Hi, I noticed that there seems to be something wrong here that is preventing the merge. Is there anything I can do? (Does Github Actions only execute the actions of the default branch of the fork, causing the robot to be unable to recognize the merge conditions?)

**Comment by curquiza** [comment]
@hanbings it's not your fault now, it's bors......

There is this "famous" error happening with external contributors sometimes, we will have to merge by hand (once we are sure the tests are correct)

Capture d’écran 2024-07-09 à 15 55 30

I re-run everything

**Comment by curquiza** [comment]
@hanbings can you rebase? we made a merge on `main` to fix the issue on the CI

**Review by curquiza — APPROVED** [review]
bors merge

**Comment by curquiza** [comment]
Ok, I tried bors but still does not work

I merge by hand since all CIs are green! Thank you @hanbings for your PR and your patience!!

**Review by lozanopo — COMMENTED** [review]
image

**Pull request merged**
