### PR TITLE
Update charabia v0.7.2

### LINKED ISSUE #3285: Upgrade dependencies
We need to update the dependencies of the Meilisearch repository, and, if possible, the dependencies of all the engine-team repositories that Meilisearch depends on (charabia, heed...).

⚠️ This issue should only be done at the beginning of the sprint!

### LINKED ISSUE #3689: Handle single quotation mark (’) and apostrophe (') the same way.
**Describe the bug**
As reported by Mason, it seems that meilisearch doesn't handle the single quotation mark (’) as apostrophe (') in v1.x.x. It appears the same with v0.29 in my test, so I think this could have been introduced in v0.29 because they are both handled the same (as `'`) in v0.28. Cross posting initial issue by Mason on [Discord](https://discord.com/channels/1006923006964154428/1006923007559729154/1095376419372155034) below:

> So we have an issue in both 1.1.0 and 1.0.2 (both instances in Meilisearch Cloud) where apostrophes (’) in queries are not treated as single quotes ('). This means that uses on iOS whose keyboards will default to an apostrophe get much worse results than users on desktop who use single quote, especially for common English-language contractions like I'm. This seems like the incorrect behavior. We can work around this with the synonyms settings for contractions like you're, but for possessive words there isn't a clear way to solve this via config, like with the book Ender's Game. We can replace apostrophes on the fly in the query before sending it the Meilisearch endpoint, but I wanted to bring this up here since this is such a common problem

**To Reproduce**
1. Index documents containing single quotation mark (’) and apostrophe ('). 
2. Search on the index. Words with single quotation marks (’) are not normalized to apostrophes ('). 

**Expected behavior**
Meilisearch should normalize single quotation mark (’) to apostrophe (') and handle both the same so they can be used interchangeably. 

**Meilisearch version:**
v1.x.x

### LINKED ISSUE #3701: Update Charabia v0.7.2
## v0.7.2 impacting changes

- Split camelCase in Latin segmenter (https://github.com/meilisearch/charabia/pull/181)
- Improve Arabic Normalizer (https://github.com/meilisearch/charabia/pull/204)
- Improve Arabic language segmentation (https://github.com/meilisearch/charabia/pull/205)
- Enhance Quotation marks support (https://github.com/meilisearch/charabia/pull/211) (Fixes #3689)

### PR DESCRIPTION
**Pull request by ManyTheFish**
fixes #3701
fixes #3689
fixes #3285

### CODE REVIEW

**Review by irevoire — APPROVED** [review]
noice bors merge

**Comment by curquiza** [comment]
@irevoire, you need to write `bors merge` in a newline, otherwise bors cannot hear you 😢 🐶 

bors merge

**Comment by curquiza** [comment]
bors merge

**Comment by curquiza** [comment]
bors merge

**Pull request merged**
