### PR TITLE
Increase max concurrent readers on indexes

### LINKED ISSUE #2786: Increase the number of concurrent reader on the indexes
In order to fix #2648 you need to find every time we open an index and update the [`EnvOpenOptions`](https://docs.rs/heed/latest/heed/struct.EnvOpenOptions.html) to add the `max_readers` option to 1024.

### PR DESCRIPTION
**Pull request by arriven**
# Pull Request

## What does this PR do?
Fixes #2786 

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Comment by hsteinmueller** [comment]
I think you only want to set `max_readers` to `1024` when opening indices, not for other options.

Would it be possible to set the option once here instead?
https://github.com/meilisearch/milli/blob/804db03e410cc282a00fc6cccf78ff88f1f0dfb3/milli/src/index.rs#L141

I'm not sure though, let's wait what the others say 😊

**Comment by arriven** [comment]
@hsteinmueller I had a thought that it would be easier to change that default in the milli repo (although I would've probably mistakenly put it in another place) but I felt like if that was a case then the issue would probably been created in that repo too

As for only setting this option when opening indices instead of all the cases, that's definitely a misinterpretation on my side, will fix soon

**Review by irevoire — COMMENTED** [review]
Thanks @arriven, that's exactly what I was expecting, I'll test your PR and come back to you on Monday :+1:

**Review by irevoire — APPROVED** [review]
Hey @arriven,

I load-tested meilisearch a little bit, and I couldn't reproduce the issue with your PR.
That's perfect thanks for your contribution!

bors merge

PS: fun fact, to test your PR, I indexed `movies.json` and tried running as many search requests as possible (and every request actually had a result in the datasets and was typed as a human).
I was able to execute 237_041 requests in 6m52s. That's an average of 575.34 requests per second, noice.

**Comment by irevoire** [comment]
Thank you for contributing to Meilisearch. If you are participating in [Hacktoberfest](https://blog.meilisearch.com/contribute-hacktoberfest-2022/), and you would like to receive some swag from Meilisearch too, please complete [this form](https://meilisearch.typeform.com/to/idt5qugY).

**Comment by Stevemoretz** [comment]
So is this PR about? https://docs.meilisearch.com/learn/advanced/known_limitations.html#maximum-number-of-concurrent-requests

Did you forget to update the docs, or is this still not released?

**Comment by Stevemoretz** [comment]
> Hello @Stevemoretz This is not released yet, we only created [a RC](https://github.com/meilisearch/meilisearch/releases/tag/v0.30.0rc0) (so not recommended to use in production). The documentation team is working on updating it with every change available in v0.30.0.
> 
> Official v0.30.0 will be released on 28th November 😊

Thanks for making it clear, really appreciated!

**Pull request merged**
