### PR TITLE
Add a specific test on finite pagination placeolder search with disti…

### PR DESCRIPTION
**Pull request by ManyTheFish**
Add a specific test on finite pagination placeholder search with distinct attributes

related to https://github.com/meilisearch/milli/pull/743
related to https://github.com/meilisearch/meilisearch/issues/3200

poke @curquiza 

> note that the destination branch should be changed

### CODE REVIEW

**Review by Kerollmops — APPROVED** [review]
Thank you very much! I let you merge it, now!

**Comment by curquiza** [comment]
Closing this since [v0.30.4](https://github.com/meilisearch/meilisearch/releases/tag/v0.30.4) is out, fixing this issue

**Comment by curquiza** [comment]
Oops, mistake on my side, I did not want to close this PR

**Comment by curquiza** [comment]
bors merge

**Comment by curquiza** [comment]
bors merge

**Pull request merged**
