### PR TITLE
Correct broken links in README

### LINKED ISSUE #4942: Broken Links in README
Within the README, there are links to many of the featuresA couple of the features links to documentation in the README are broken:

- [Typo Tolerance](https://www.meilisearch.com/docs/learn/configuration/typo_tolerance) gets a 404, as `Typo_Tolerance` is not a documentation article. It should probably link to  `https://www.meilisearch.com/docs/learn/relevancy/typo_tolerance_settings`
- [Synonym Support](https://www.meilisearch.com/docs/learn/configuration/synonyms) gets a 404, as `Synonyms` is not a documentation article. It should probably link to `https://www.meilisearch.com/docs/learn/relevancy/synonyms`
- [Multi-Tenancy](https://www.meilisearch.com/docs/learn/security/tenant_tokens) gets a 404, as `Tenant_Tokens` is not a documentation article. It should probably link to `https://www.meilisearch.com/docs/learn/security/multitenancy_tenant_tokens`

### PR DESCRIPTION
**Pull request by iornstein**
# Pull Request

## Related issue
Fixes #4942

## What does this PR do?
- Corrects some broken links in the README. My suspicion is that some of these documentation articles were moved around without someone updating links in the README.

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)? _(well the contributing guidelines led me to create an issue first)_
- [x] Have you read the contributing guidelines? _yes_
- [x] Have you made sure that the title is accurate and descriptive of the changes? _yes_

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Review by Kerollmops — APPROVED** [review]
Thank you very much for these fixes mate 👋
bors merge

**Comment by curquiza** [comment]
bors merge

**Comment by curquiza** [comment]
bors merge

**Comment by iornstein** [comment]
Is there a flaky test in the [Tests on windows-2022] test suite? It looks like originally the pull request failed due to that test suite failing. Which is odd, since the change set was entirely non-code. And it looks like now after running again it passed that test suite.

Or is there another expected reason for this test behavior?

@Kerollmops @curquiza

**Comment by curquiza** [comment]
@iornstein yes sorry, it's not you, it's our tests 🫠

**Comment by iornstein** [comment]
Ah yes, I've been there (flaky test land) before.

**Pull request merged**
