### PR TITLE
URL encode search in web UI

### LINKED ISSUE #986: `&` Breaks Search on Dashboard
**Describe the bug**
When entering a search in the provided MeiliSearch dashboard the search is broken, returning a 400 error as the `&` breaks the search request URL. This is because the search string is not URL encoded using `encodeURIComponent(search.value)`.

- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the MeiliSearch dashboard: http://localhost:7700
2. Enter a search with an ampersand (`&`) in it.
3. See the search does not complete and a 400 error is returned in the network tab

**Expected behaviour**
A search with an ampersand should work and the & should be URL encoded.

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7 (19H2)
 - Browser Firefox
 - Version 82.0b4 (64-bit)

### PR DESCRIPTION
**Pull request by akrantz01**
Fixes #986

### CODE REVIEW

**Comment by LegendreM** [comment]
bors try

**Review by LegendreM — APPROVED** [review]

**Comment by LegendreM** [comment]
Hello @akrantz01 thank you for your contribution,

Is it the #Hacktoberfest that make you discover meilisearch?

**Comment by akrantz01** [comment]
> Is it the #Hacktoberfest that make you discover meilisearch?

No, I first discovered meilisearch a while ago on r/rust. Since then I've just been watching from afar and reading many of the blog posts.

**Pull request merged**
