### PR TITLE
One click deploy to Render.com

### PR DESCRIPTION
**Pull request by arnaudDerbey**
Bonjour ! 
Just want to provide another easy way to deploy Meilisearch. Add a one click button to deploy on Render with persistent data storage. A master key is auto generated for security and can be found in the dashboard. 

You can test the integration [here](https://github.com/arnaudDerbey/meilirender/blob/main/README.md).

### CODE REVIEW

**Comment by Ajju2211** [comment]
How to find masterkey

**Review by Ajju2211 — APPROVED** [review]
render.com is also better platform.
Please accept these changes

**Comment by fharper** [comment]
@Kerollmops, please add someone else if you aren't the one who can review this PR.

@arnaudDerbey @Ajju2211 we will review this PR when the core team is back from the holidays, thanks for your help!

**Comment by tpayet** [comment]
Hey!
Thanks for this pull request, but we should add different ways of installing MeiliSearch in the documentation instead of the README of the project. We might have too many informations in this README and 7 or 8 different ways of installing are too much. We would love to add this render deploy to our documentation if you [could make the pull request](https://github.com/meilisearch/documentation/edit/master/guides/advanced_guides/installation.md) or [we will do it at some point](https://github.com/meilisearch/documentation/issues/620).

We should close this PR on this repository for now.

Thanks again :)

**Comment by fharper** [comment]
Adding @react-learner to this thread so he can help with the documentation part. If we add more ways to install in the documentation, we should link to them int he README. Speaking of having too much stuff in the README, you are right, I'll give it a closer look and make recommandations soon.

**Comment by MarinPostma** [comment]
closing this pr as per @tpayet  suggestion, please reopen if necessary in the documentation repository

**Pull request closed without merging**
