### PR TITLE
Reduce `Transform`'s disk usage

### PR DESCRIPTION
**Pull request by Kerollmops**
This PR implements what is described in #4485. It reduces the number of disk writes and disk usage.

### CODE REVIEW

**Comment by dureuill** [comment]
Would be great to devise benchmark workloads to measure the impact on performance of this change

**Comment by dureuill** [comment]
Looking at the latest bench invocation, looks like there are some regressions compared with the run on the previous commit.

- settings-add-embeddings-hf 
  - [main](https://bench.meilisearch.dev/view_spans?commit_sha1=516268addf68913927e87c999e51fab3ec444643&workload_name=settings-add-embeddings-hf&target_branch=reduce-transform-disk-usage&baseline_branch=main): negligible change
  - [previous commit](https://bench.meilisearch.dev/view_spans?commit_sha1=516268addf68913927e87c999e51fab3ec444643&workload_name=settings-add-embeddings-hf&target_branch=reduce-transform-disk-usage&baseline_branch=reduce-transform-disk-usage) negligible change
- settings-add-remove-filters.json 
  - [main](https://bench.meilisearch.dev/view_spans?commit_sha1=516268addf68913927e87c999e51fab3ec444643&workload_name=settings-add-remove-filters.json&target_branch=reduce-transform-disk-usage&baseline_branch=main): **regression 10s**
  - [previous commit](https://bench.meilisearch.dev/view_spans?commit_sha1=516268addf68913927e87c999e51fab3ec444643&workload_name=settings-add-remove-filters.json&target_branch=reduce-transform-disk-usage&baseline_branch=reduce-transform-disk-usage): **regression 14s**: biggest regressions are in extract_word_docids, index_documents_raw , extract_docid_word_positions and write_entries_into_db
- settings-proximity-precision.json
  - [main](https://bench.meilisearch.dev/view_spans?commit_sha1=516268addf68913927e87c999e51fab3ec444643&workload_name=settings-proximity-precision.json&target_branch=reduce-transform-disk-usage&baseline_branch=main): improvements 1s
  - [previous commit](https://bench.meilisearch.dev/view_spans?commit_sha1=516268addf68913927e87c999e51fab3ec444643&workload_name=settings-proximity-precision.json&target_branch=reduce-transform-disk-usage&baseline_branch=reduce-transform-disk-usage): **regression 2s** 
- settings-remove-add-swap-searchable.json 
  - [main](https://bench.meilisearch.dev/view_spans?commit_sha1=516268addf68913927e87c999e51fab3ec444643&workload_name=settings-remove-add-swap-searchable.json&target_branch=reduce-transform-disk-usage&baseline_branch=main): improvement 2s
  - [previous commit](https://bench.meilisearch.dev/view_spans?commit_sha1=516268addf68913927e87c999e51fab3ec444643&workload_name=settings-remove-add-swap-searchable.json&target_branch=reduce-transform-disk-usage&baseline_branch=reduce-transform-disk-usage): **regression 2.5s**
- settings-typo.json  
  - [main](https://bench.meilisearch.dev/view_spans?commit_sha1=516268addf68913927e87c999e51fab3ec444643&workload_name=settings-typo.json&target_branch=reduce-transform-disk-usage&baseline_branch=main): improvement 1.8s
  - [previous commit](https://bench.meilisearch.dev/view_spans?commit_sha1=516268addf68913927e87c999e51fab3ec444643&workload_name=settings-typo.json&target_branch=reduce-transform-disk-usage&baseline_branch=reduce-transform-disk-usage): negligible change

**Comment by dureuill** [comment]
I'm loving the results I'm seeing ❤️

**Comment by Kerollmops** [comment]
bors merge

**Comment by ManyTheFish** [comment]
BORS MERGE

**Comment by Kerollmops** [comment]
bors merge

**Pull request merged**
