### PR TITLE
Add MeiliSearch version to issue template

### PR DESCRIPTION
**Pull request by bidoubiwa**
It is relevant to know the version of MeiliSearch before any other additional information that might be important to know.

We could also reduce the number of required information asked to the user. I would like to suggest the following:

Instead of the section of `Desktop` and `Smartphone`  I would just improve the last section

```
**Additional context**
Additional information that may be relevant to the issue.
[e.g. architecture, device, OS, browser]
```

By applying this, the template final look will be the following: 

-----

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**MeiliSearch version:** [e.g. v0.20.0]

**Additional context**
Additional information that may be relevant to the issue.
[e.g. architecture, device, OS, browser]

### CODE REVIEW

**Review by MarinPostma — APPROVED** [review]

**Comment by irevoire** [comment]
I just wanted to say that I also think we should reduce the number of required information asked to the user. 
I feel like seeing these two large blocks at the end:
```
**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]
```

That ask for “hard” to retrieve information like the version of your browser is discouraging to the user while in reality, the probability it helps us is minimal.

If someone is using some esoteric setup like a *BSD or a pi, I think he'll probably know that it could be relevant information and write it himself in the “Additional context”

**Comment by bidoubiwa** [comment]
@irevoire I have updated the changes accordingly :) It has been approved. I don't have merge rights so I let you do it

**Review by irevoire — APPROVED** [review]
bors merge

**Comment by MarinPostma** [comment]
bors merge

**Comment by MarinPostma** [comment]
bors merge

**Comment by irevoire** [comment]
bors merge

**Comment by irevoire** [comment]
it was so easy to merge

**Pull request merged**
