### PR TITLE
Use bumparaw-collections in Meilisearch/milli

### PR DESCRIPTION
**Pull request by Kerollmops**
This PR is related to #5078. It uses the now published bumparaw-collections and (soon) makes the `RawMap` hasher nonrandom.

### CODE REVIEW

**Comment by Kerollmops** [comment]
/bench workloads/hackernews-add-new-documents.json workloads/hackernews-modify-*

**Comment by Kerollmops** [comment]
/bench workloads/hackernews-add-new-documents.json workloads/hackernews-modify-*

**Comment by Kerollmops** [comment]
/bench workloads/hackernews-add-new-documents.json workloads/hackernews-modify-*

**Review by dureuill — APPROVED** [review]
bors merge

**Pull request merged**
