### PR TITLE
Improve the way we receive the documents payload- serde multiple ndjson fix

### LINKED ISSUE #3037: Improve the way we receive the documents payload
We currently use the above-linked method to receive the documents payload sent by the users. This function stores everything into memory, this is not optimal, we could probably do much better and stream that to disk at least with [a `BufWriter` or equivalent](https://doc.rust-lang.org/std/io/struct.BufWriter.html).

https://github.com/meilisearch/meilisearch/blob/9e189f5041fad0312fc0aa94038a890ad922e92c/meilisearch-http/src/routes/indexes/documents.rs#L197-L293

### PR DESCRIPTION
**Pull request by jiangbo212**
# Pull Request

## Related issue
Fixes #3037 

## Related PR
#3164 

## What does this PR do?
Sorry, This PR is mainly to fix the problems caused by my previously provided PR #3164. It causes multiple ndjson data deserialization failures
- Fix serde multiple ndjson data failures and add test to it
- Fix serde jsonarray error and againest serde it use `from_slice`. only use `from_slice` when serde error category is `data`, it indicate json data is a single json.

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Review by Kerollmops — APPROVED** [review]
Tested it on my machine with simple datasets, and it is working great!
Could you please tell me what you fixed precisely?

**Comment by jiangbo212** [comment]
The first fix is serde deserialize multiple ndjson data exception, for example the following ndjson data

https://github.com/meilisearch/meilisearch/blob/2780e365e279c8ce94aaeae905fde8e7b8452150/meilisearch/tests/assets/test_set.ndjson#L1-L4

under main branch, using the following curl command, we will get an exception. But it is actually the correct ndjson data.

```shell
curl   -X POST 'http://localhost:7700/indexes/isbn001/documents?primaryKey=isbn'   -H 'Content-Type: application/x-ndjson'   --data-binary @/home/lighthouse/isbndb/test_set.ndjson
```

The second fix involves serde deserialization of json data

When the data is in json format, we first try to deserialize the json data using array_each. For example, in the json data below, we will get an error when we use array_each.

```json
[
{"id": 0, "field1": "field1"},
{"id": 1, "field1": "field2"}
```

In the main branch, we will continue to use from_reader to deserialize. When this error data is very large, it will take a lot of time. Here I made a fix to continue deserializing using single json only when array_each throws a non-seq data error.

**Comment by Kerollmops** [comment]
> The first fix is serde deserialize multiple ndjson data exception, for example the following ndjson data

Indeed the payload of the request is ND-JSON valid and should be accepted, thank you very much. I just tested and this branch fixes the issue.

```json5
# on main
# curl -X POST 'http://localhost:7700/indexes/isbn001/documents?primaryKey=isbn' -H 'Content-Type: application/x-ndjson' --data-binary @test_set.ndjson
{"message":"The `ndjson` payload provided is malformed. `Couldn't serialize document value: trailing characters at line 2 column 1`.","code":"malformed_payload","type":"invalid_request","link":"https://docs.meilisearch.com/errors#malformed_payload"}
```

```json5
# on this branch
# curl -X POST 'http://localhost:7700/indexes/isbn001/documents?primaryKey=isbn' -H 'Content-Type: application/x-ndjson' --data-binary @test_set.ndjson
{"taskUid":0,"indexUid":"isbn001","status":"enqueued","type":"documentAdditionOrUpdate","enqueuedAt":"2023-01-05T10:40:13.443554Z"}
```

> The second fix involves serde deserialization of json data

Thank you very much, it also works on my side and is more related to big payloads this time!

I am very pleased by what you've done and happy that you explained the issue more precisely 🎉
bors merge

**Review by Kerollmops — APPROVED** [review]
bors merge

**Comment by curquiza** [comment]
bors merge

**Pull request merged**
