### PR TITLE
Fixup dumps-destination -> dump-directory section header in help link

### PR DESCRIPTION
**Pull request by dureuill**
# Pull Request

## Related issue
See https://github.com/meilisearch/product/discussions/560#discussioncomment-4323938

## What does this PR do?
- change link in help message to the future new section header #dump-directory

### CODE REVIEW

**Review by irevoire — COMMENTED** [review]
From what I see in the documentation, it's still dumps-destination.
Should we wait before merging?

**Comment by dureuill** [comment]
Yes, that was [my question](https://github.com/meilisearch/product/discussions/560#discussioncomment-4324076) too (sorry should have repeated it here).

I don't know what the process is for changing documentation-related links that appear in the meilisearch repo, usually

**Comment by curquiza** [comment]
Hum, you are right, the documentation is using the config.toml on `main`
So we need to change this once v1 is released on the documentation side

**Comment by curquiza** [comment]
I've added "merge this PR once documentation for v1 is deployed", be sure I will not forget it 😉

**Comment by irevoire** [comment]
Putting this as a draft so we don't merge it by error

**Comment by dureuill** [comment]
Rebased on `main` to integrate the other changes to the config file (removal of size options, merge of snapshot scheduling options, removal of `--disable-auto-batching`)

**Review by curquiza — APPROVED** [review]
v1.0 is released so let's merge this

**Comment by curquiza** [comment]
bors merge

**Comment by curquiza** [comment]
bors merge-

**Comment by curquiza** [comment]
Waiting for docs deployment before 😅 my bad!

**Comment by curquiza** [comment]
bors merge

**Pull request merged**
