### PR TITLE
Update link after branch renaming

### PR DESCRIPTION
**Pull request by curquiza**

### CODE REVIEW

**Comment by curquiza** [comment]
bors try

**Comment by curquiza** [comment]
bors try

**Review by MarinPostma — APPROVED** [review]
bors merge

**Comment by curquiza** [comment]
bors merge

**Comment by curquiza** [comment]
bors try

**Comment by curquiza** [comment]
bors merge

**Review by MarinPostma — APPROVED** [review]
bors merge

**Pull request merged**
