### PR TITLE
fix(rebranding): Update the ascii art

### PR DESCRIPTION
**Pull request by irevoire**

### CODE REVIEW

**Review by curquiza — APPROVED** [review]
Thanks @irevoire ❤️ 

bors merge

**Comment by curquiza** [comment]
Suprised you did not take the opportunity to write "Mielisearch" instead

**Comment by curquiza** [comment]
bors merge

**Comment by Kerollmops** [comment]
bors merge

**Comment by curquiza** [comment]
bors merge

**Pull request merged**
