### PR TITLE
Better dependencies cache for CI

### PR DESCRIPTION
**Pull request by shekhirin**

### CODE REVIEW

**Review by irevoire — APPROVED** [review]
Thank you :1st_place_medal: 

bors merge

**Comment by irevoire** [comment]
bors cancel

**Comment by irevoire** [comment]
@curquiza do we want to merge this PR on the releasev0.22 branch?

**Comment by curquiza** [comment]
@irevoire, nope, this will be for v0.23.0 🙂
Plus we have an issue currenlty on the CI (many is working on the fix right now) so you will not be able to merge it ;)

**Comment by curquiza** [comment]
bors merge

**Pull request merged**
