### PR TITLE
Use the milli's heed dependency

### LINKED ISSUE #2210: Use the milli's heed dependency
Discussed with @Kerollmops 
[As we did for the tokenizer](https://github.com/meilisearch/meilisearch/pull/1970), we want to use the heed dependency from Milli's side to avoid having different versions of Heed in Meilisearch. Indeed compilation will fail if we have different versions of heed in Meilisearch and in Milli.
- [x] Export heed on Milli's side
- [x] Use the exported Heed dependency in Meilisearch

### PR DESCRIPTION
**Pull request by psvnlsaikumar**
# Pull Request

## What does this PR do?
Fixes #2210

This PR (https://github.com/meilisearch/milli/pull/464) is to be merged before approving this. 
## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Comment by psvnlsaikumar** [comment]
Resolved merge conflicts in PR

**Comment by MarinPostma** [comment]
hey @psvnlsaikumar ! Thanks so much for contributing! Could you squash all your commits into one please?

**Comment by MarinPostma** [comment]
@psvnlsaikumar, I need this merged ASAP, so what I am gonna do is merge this branch into another branch, make my fixes there, and merge it in main afterward. This way your work will be present in main, while I get my merge on time :)

Thanks again for your contribution :)

**Comment by psvnlsaikumar** [comment]
Sure @MarinPostma . That works. I was going to get the work done tonight. But if you are going to take care of it then sure. FYI, the version of milli is to updated once we have the newer version or milli with the recent changes( export of heed) available.

**Comment by MarinPostma** [comment]
@psvnlsaikumar  yes, that should be done this afternoon

**Pull request merged**
