### PR TITLE
Add missing Korean support

### PR DESCRIPTION
**Pull request by junhochoi**
Some configuration is missing `korean` features and add a test case in `milli/src/search/mod.rs`.

# Pull Request

## Related issue

#3443 #3882 

## What does this PR do?
- Improvement on enabling Korean support

Inspired by the work (#3882) I tried to enable Korean features but have found some missing configurations.
This PR is add those missing configs (mostly Cargo.toml) and added one test case.

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Review by ManyTheFish — APPROVED** [review]
Hello @junhochoi,

I approve this PR, sorry for the delay..

bors merge

**Comment by ManyTheFish** [comment]
bors cancel

**Comment by ManyTheFish** [comment]
bors merge

**Comment by junhochoi** [comment]
Rebased.

**Comment by curquiza** [comment]
@junhochoi don't worry, it's not about your PR, but our CI, we will merge your PR next week 😊

**Comment by ManyTheFish** [comment]
bors merge

**Pull request merged**
