### PR TITLE
Sample Changes For Rust Destructuring

### LINKED ISSUE #3928: Rewrite the `segment_analytics` module with the destructuring syntax
The segment_analytics module has been written so that we can omit using fields from the query or the Aggregator struct itself. We must rewrite it with [the Rust Destructuring syntax](https://doc.rust-lang.org/rust-by-example/flow_control/match/destructuring/destructure_structures.html) to be sure to have an error when we forget to use a field and do something with it explicitly.

I no more want to have to do [this kind of PR](https://github.com/meilisearch/meilisearch/pull/3909) in the middle of the pre-release cycle.

https://github.com/meilisearch/meilisearch/blob/2b4160ebb95b7ec3c46f3b7ce5735013d47a9500/meilisearch/src/analytics/segment_analytics.rs#L613-L681

### PR DESCRIPTION
**Pull request by postmeback**
# Pull Request

## Related issue
Fixes #3928

## What does this PR do?
As suggested, I have tried to use Rust Destructing in the specified rust file. Requesting for review. If the changes are fine. I would like to modify in some other places of the same file as well.

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Comment by postmeback** [comment]
Explanation:

In the old code, the **from_query** function used a mutable reference `(&mut self)` to modify the fields of the **DocumentsDeletionAggregator** struct individually based on the value of kind. This required multiple if-else conditions to check the value and assign the corresponding field.

In the updated code, the from_query function uses pattern matching (match) to assign the appropriate values to **per_document_id**, **clear_all**, **per_batch**, and **per_filter** based on the value of kind. This results in more concise and readable code.

The remaining code for the aggregate and into_event functions remains the same in both the old and updated versions.

The updated code improves readability and reduces the duplication of code by using pattern matching, making it easier to understand and maintain the logic for handling different cases of kind.

**Comment by postmeback** [comment]
Could not understand why `rustfmt` is failing

**Comment by Kerollmops** [comment]
> Could not understand why `rustfmt` is failing

Could you use `cargo +nightly fmt` on the project, as we use some nightly formatting rules? To be able to run this command, please install a nightly toolchain by doing `rustup install nightly`.

Furthermore, could you do a big restructuring of the `SearchQuery` struct in the `from_query` method like we [do with this type](https://github.com/meilisearch/meilisearch/blob/13a13a486211e9ec79047078e17719c92f838150/meilisearch/src/analytics/segment_analytics.rs#L476-L545), please? This way, we always remember an added field in the analytics.

Could you also do the same in the `SearchAggregator::aggregate`, and `SearchAggregator::into_event` methods and do the same for the `MultiSearchAggregator` methods, too, please?

**Comment by postmeback** [comment]
Thanks for the input. Give me some time, I will do and update the PR. 

✌🏾

**Comment by postmeback** [comment]
As requested, all the changes are done. Requesting for review

**Comment by Kerollmops** [comment]
Hey @postmeback 👋

Unfortunately, that is not what I requested. I was probably not clear enough, but the issue is that the `SearchQuery` struct is modified. We often forgot to update the `SearchAggregator::from_query` function.

To be sure that we don't forget again about that, could you destructure the `SearchQuery` (that is identified as `query` in the `from_query` function)? This way, the compiler will throw an error if we forgot a field.

```rust
// like this
let SearchQuery { q, vector, a_field_that_we_explicitly_ignore: _ } = query;

// and not like this.
// if you do that, any new field will be ignored by default.
let SearchQuery { q, vector, ... } = query;
```

**Review by Kerollmops — CHANGES_REQUESTED** [review]
Hey @postmeback 👋

Unfortunately, that is not what I requested. I was probably not clear enough, but the issue is that the `SearchQuery` struct is modified. We often forgot to update the `SearchAggregator::from_query` function.

To be sure that we don't forget again about that, could you destructure the `SearchQuery` (that is identified as `query` in the `from_query` function)? This way, the compiler will throw an error if we forgot a field.

```rust
// like this
let SearchQuery { q, vector, a_field_that_we_explicitly_ignore: _ } = query;

// and not like this.
// if you do that, any new field will be ignored by default.
let SearchQuery { q, vector, ... } = query;
```

**Comment by postmeback** [comment]
Give me some time, I will change it.

Are you okay, with the other set of changes?

**Comment by postmeback** [comment]
As requested, `SearchQuery` is destructured

**Comment by postmeback** [comment]
Hi @Kerollmops , requesting for review.

**Comment by curquiza** [comment]
@postmeback
@Kerollmops is on Holiday and will come back in a couple of weeks 😊

**Comment by postmeback** [comment]
Okay. 😃

**Comment by postmeback** [comment]
Hey, is this change good to go?

**Comment by postmeback** [comment]
Hey, are the changes fine ?

**Comment by Kerollmops** [comment]
Thanks @postmeback! Would it be possible to rebase on the `main` branch, please?

**Comment by postmeback** [comment]
I am finding it difficult. Can you help ?

**Comment by Kerollmops** [comment]
Hey @postmeback 👋

You should probably read [this tutorial guide](https://git-scm.com/book/en/v2/Git-Branching-Rebasing) explaining how to rebase your branch on `main`/`master` first. If you don't succeed by following it, I advise you to either merge `main` into your branch or start from a fresh branch from `main`.

**Comment by Kerollmops** [comment]
Thank you very much for your help. Unfortunately, [someone else fixed the issue and we merged the changes](https://github.com/meilisearch/meilisearch/pull/4056).
Sorry, I hope you'll be able to work on some other issue next ❤️

**Comment by postmeback** [comment]
Okay 👍🏾

**Pull request closed without merging**
