### PR TITLE
🐞 fix: Support https in print_launch_resume

### LINKED ISSUE #2660: Address in the launch resume is always http (even if https is used)
**Describe the bug**
When starting you get an resume on how Meilisearch is started. The contains always contains http even if the https certificates are configured AND the webservers listens to https.

**To Reproduce**
1. Start with: `meilisearch --http-addr=127.0.0.1:7700 --ssl-cert-path ./127.0.0.1.pem --ssl-key-path ./127.0.0.1-key.pem`
2. "Server listening on: "**http**://127.0.0.1:7700"

**Expected behavior**
"Server listening on" should use https

**Meilisearch version:** 0.28.1

**Additional context**
The `print_launch_resume` method contains a static string for the protocol. 
https://github.com/meilisearch/meilisearch/blob/09ec8e9fcad95d9f742106afa24fbdf2866f76f1/meilisearch-http/src/main.rs#L119

### PR DESCRIPTION
**Pull request by evpeople**
fix #2660

# Pull Request

## What does this PR do?
Fixes #2660 

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Comment by ManyTheFish** [comment]
Hello @evpeople, thank you for your PR! You have some clippy and rustfmt errors, I let you fix them before merging your work 👍

**Comment by evpeople** [comment]
the clippy error is about meilisearch-types/src/index_uid.rs.which I didn't change，so the style commit also didn't change the `index_uid.rs`.

To pass the cargo clippy I add Eq trait on IndexUid, but It add more warnings,

Now I have deleted the Eq clippy on IndexUid 
[here is the clippy when I added Eq trait on IndexUid](https://github.com/evpeople/meilisearch/runs/7802718625)

**Comment by evpeople** [comment]
I have checked other PR，their IndexUid derive PartialEq not Eq just as mine, but they have passed  the check , I really wander why.

**Comment by irevoire** [comment]
Oh, @evpeople, you’re right. It has nothing to do with your PR.
It’s because there was an update of Clippy yesterday that added a bunch of new warnings 😒 
I’ll make a PR to fix all the Clippy warnings and then you can rebase on it before merging, you should have no conflicts from what I see 👍 

Thanks for you contribution

**Comment by evpeople** [comment]
Got it

**Comment by irevoire** [comment]
bors merge

**Review by irevoire — APPROVED** [review]
bors merge

**Pull request merged**
