### PR TITLE
Replace hardcoded string with constants

### LINKED ISSUE #5136: Add a constant value for the "_geo" reserved field
Unlike the `"_vector"` reserved field (`RESERVED_VECTORS_FIELD_NAME`) the field `"_geo"` field has no associated constant value and is hardcoded everywhere it's used.

- [ ] Add a `RESERVED_GEO_FIELD_NAME` in milli
- [ ] Replace all the hardcoded occurrences of "_geo" by the newly created constant

### PR DESCRIPTION
**Pull request by Gnosnay**
# Pull Request

## Related issue
Fixes #5136

## What does this PR do?
- Replace all of hardcoded "_geo" to one constant string.

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Comment by irevoire** [comment]
Hey @Gnosnay, I just reviewed your PR and it's perfect as-is.
We have a big rebase of `release-v1.12.0` on main planned by the end of the week and I would like to make it as smooth as possible since the code is quite complex.
If that works for you, I would like to merge your PR after the rebase at the beginning of next week :pray:

**Comment by Gnosnay** [comment]
> Hey @Gnosnay, I just reviewed your PR and it's perfect as-is. We have a big rebase of `release-v1.12.0` on main planned by the end of the week and I would like to make it as smooth as possible since the code is quite complex. If that works for you, I would like to merge your PR after the rebase at the beginning of next week 🙏

thx for your reply. sure~ it is okie to me.

**Comment by Gnosnay** [comment]
do let me know if this pr requires more help to be proceeded

**Comment by irevoire** [comment]
Hey @Gnosnay, it's done: https://github.com/meilisearch/meilisearch/pull/5187
The change of the last release was brought to main, and you can rebase, then I'll merge your PR.
Thanks again for your interest in the project!

**Comment by Gnosnay** [comment]
> Hey @Gnosnay, it's done: #5187 The change of the last release was brought to main, and you can rebase, then I'll merge your PR. Thanks again for your interest in the project!

@irevoire hi master, i rebased the branch, pls help have one look. many thanks

**Review by irevoire — CHANGES_REQUESTED** [review]
Hey @Gnosnay, from what I see, this looks good to merge.
The only issue left is that clippy and rustfmt are complaining.
You can run clippy by simply running: `cargo clippy`.
And to run rustfmt you need to execute the following command: `cargo +nightly fmt`

**Comment by Gnosnay** [comment]
hi  @irevoire , thank you for your reply. i have fixed the format issue. please have one look.

happy holiday btw

**Review by irevoire — APPROVED** [review]
Thank you @Gnosnay, that's perfect :heart_hands: 

bors merge

**Pull request merged**
