### PR TITLE
remove the sys-info routes

### LINKED ISSUE #808: Remove /sys-info routes
As discussed with @Kerollmops , there are issues with this route, that often return garbage values. the added value of this route is a very low since there are many tools that are much better suited for this job. It appears that this route require more maintenance than we anticipated, and for these reasons 

I suggest that we remove it.

### PR DESCRIPTION
**Pull request by MarinPostma**
close #808

### CODE REVIEW

**Comment by curquiza** [comment]
Can you add the label `meilisearch-http` since this PR is added to the Milestones v0.13.0 but not the issue? 🙂

**Comment by MarinPostma** [comment]
Sorry, I have to get used to this ;)

**Comment by MarinPostma** [comment]
@Kerollmops done

**Comment by Kerollmops** [comment]
@MarinPostma nope ;)

**Comment by MarinPostma** [comment]
bors merge

**Comment by MarinPostma** [comment]
bors merge

**Comment by MarinPostma** [comment]
bors merge

**Comment by MarinPostma** [comment]
bors merge

**Comment by MarinPostma** [comment]
bors merge

**Comment by MarinPostma** [comment]
bors merge

**Comment by MarinPostma** [comment]
bors merge

**Comment by MarinPostma** [comment]
bors merge

**Comment by MarinPostma** [comment]
bors try

**Pull request merged**
