### PR TITLE
Fix soft deleted bug settings

### PR DESCRIPTION
**Pull request by Kerollmops**
This PR fixes https://github.com/meilisearch/meilisearch/issues/3021 and fixes https://github.com/meilisearch/meilisearch/issues/2945 and is released as version 0.29.2.

### CODE REVIEW

**Review by ManyTheFish — DISMISSED** [review]
looks good!

bors merge

**Review by dureuill — DISMISSED** [review]
Cargo.lock appears clean! looks good to me

**Review by dureuill — DISMISSED** [review]

**Review by curquiza — APPROVED** [review]
bors merge

**Comment by curquiza** [comment]
@Kerollmops Clippy is not working

**Review by curquiza — APPROVED** [review]
bors merge

**Pull request merged**
