### PR TITLE
fix running URL display

### PR DESCRIPTION
**Pull request by fharper**
by doing that you can just click on it in the terminal if you want

### CODE REVIEW

**Comment by fharper** [comment]
@MarinPostma I cannot compile MeiliSearch on my computer, so I wasn't able to test, but I assume it will work since I just updated a string...

Also, let me know if I needed to tag someone else.

**Comment by MarinPostma** [comment]
Uhm would that work with tls?

**Comment by fharper** [comment]
You may have a warning as I changed only the display of the running URL.

**Review by curquiza — APPROVED** [review]
checked with @qdequele!
bors merge

**Pull request merged**
