### PR TITLE
bump dependencies

### PR DESCRIPTION
**Pull request by MarinPostma**
Bump meilisearch dependencies.

We still depend on custom patch that have been upgraded along the way.

### CODE REVIEW

**Comment by irevoire** [comment]
Isn't this PR supposed to be merged into releasev0.22 or something?
Because we are missing [this PR](https://github.com/meilisearch/MeiliSearch/commit/49c918defa34264f4085fe24dbb2cd508a7a8103), which was bumping milli and is in conflict with this one.

**Comment by MarinPostma** [comment]
it needs a rebase

**Review by irevoire — APPROVED** [review]
Looks good to me!

**Comment by MarinPostma** [comment]
bors merge

**Review by irevoire — APPROVED** [review]

**Comment by MarinPostma** [comment]
bors merge

**Pull request merged**
