### PR TITLE
Update dashboard for v0.25.0

### PR DESCRIPTION
**Pull request by mdubus**

### CODE REVIEW

**Review by curquiza — CHANGES_REQUESTED** [review]
The placeholder search does not work for me :(

Capture d’écran 2022-01-10 à 12 27 21

**Comment by curquiza** [comment]
Ok, I don't understand, now it works

**Review by Kerollmops — DISMISSED** [review]
Apart from the fact that the movies dataset available on the README has broken image links, everything looks good to me, the placeholder works fine. Nice work :tada:

**Review by curquiza — APPROVED** [review]
thaaaaaanks @mdubus!

bors merge

**Pull request merged**
