### PR TITLE
Bug(auth): Parse YMD date

### LINKED ISSUE #2017: v0.25.0 RC Post key by sending only the date part `YYYY-MM-DD` failed
**Describe the bug**

Post a new key by sending only the date part for `expiresAt` field failed.
According to the [API Keys](https://github.com/meilisearch/specifications/blob/develop/text/0085-api-keys.md#155-post-patch---keys---api-key-object-payload-definition) specification and the API response, the `expiresAt` value can be defined only with the date such as: `YYYY-MM-DD`.

| field       | type    | required |description                     |
|-------------|---------|----------|--------------------------------|
| expiresAt   | string  | Required | The expiration date and time as `ISO-8601` format. `null` equals to no expiration time. Sending only the date part e.g `2021-12-01` leads to having an `expiresAt` value set to `2021-12-01T00:00:00`. **Default**: `No Default` |

**To Reproduce**

*Post on `/keys` route:*
```json
{
    "description": "Indexing Products API key",
    "actions": [
        "documents.add"
    ],
    "indexes": ["products"],
    "expiresAt": "2022-01-01"
}
```
*Response:*
```json
{
	"message": "expiresAt field value `\"2022-01-01\"` is invalid. It should be in ISO-8601 format to represents a date or datetime in the future or specified as a null value. e.g. 'YYYY-MM-DD' or 'YYYY-MM-DDTHH:MM:SS'.",
	"code": "invalid_api_key_expires_at",
	"type": "invalid_request",
	"link": "https://docs.meilisearch.com/errors#invalid_api_key_expires_at"
}
```

**Expected behavior**

The `expiredAt` must be able to be defined by a date format or the API message must be modified.

**MeiliSearch version:** v0.25.0rc1

### LINKED ISSUE #2024: v0.25.0 RC: `documents.add` right should not allow to create indexes
We identified a potential security issue regarding the access rights when using API keys.

Only available in v0.25.0 release candidates at the moment, so no issue for our users in production since we strongly do not recommend using RCs in production. 

When creating this kind of API key

```json
{
    "description": "Key to add documents for all the indexes.",
    "actions": [
        "documents.add"
    ],
    "indexes": [
        "*"
    ],
    "expiresAt": null
}
```

Currently, with this key, I can add documents in every index, but also, I can create as many indexes as I want, without the `indexes.create` right.
This is due to the implicit index creation: when adding documents, MeiliSearch automatically creates an index if it does not exist.

### Solution

We chose to make the API return an asynchronous error: when getting the task information using the `GET /tasks/:task_uid` route, the user will see an `Index not found error`.

The solution we decided to implement is not perfect since it can bring some user experience frustration, but we would rather a user frustration than a security issue for this first implementation of the API keys.

### PR DESCRIPTION
**Pull request by ManyTheFish**
Use NaiveDate to parse YMD date instead of NaiveDatetime

fix #2017

### CODE REVIEW

**Review by MarinPostma — APPROVED** [review]

**Comment by ManyTheFish** [comment]
bors merge

**Comment by curquiza** [comment]
bors merge

**Comment by ManyTheFish** [comment]
bors try

**Comment by curquiza** [comment]
bors merge

**Pull request merged**
