### PR TITLE
Explicitly check permissions when receiving a slash command

### PR DESCRIPTION
**Pull request by dureuill**
- Checks used to be implicitly done inside the referenced github actions
- Improves error message and clarity of intent

### CODE REVIEW

**Comment by curquiza** [comment]
@dureuill can you run the benchmarks on this branch to check it's working?

**Review by curquiza — APPROVED** [review]
Let's merge and try next 🤓

**Review by Kerollmops — APPROVED** [review]
LGTM

**Comment by curquiza** [comment]
bors merge

**Pull request merged**
