### PR TITLE
Change links of docs everywhere

### LINKED ISSUE #3668: Update messages pointing to the docs website
**Describe the bug**
The new documentation website changed its URL from https://docs.meilisearch.com to https://meilisearch.com/docs. Additionally, we have dropped `.html` extensions from all our links.

These two changes should be reflected in any messages referencing the docs site.

**To Reproduce**
For example, when a user launches `meilisearch`, the welcome message includes this paragraph:

`We collect anonymized analytics to improve our product and your experience. To learn more, including how to turn off analytics, visit our dedicated documentation page: https://docs.meilisearch.com/learn/what_is_meilisearch/telemetry.html`

I'm sure there are many others across the codebase that I'm not immediately aware of.

**Expected behavior**
The updated launch message should look something like this:

`We collect anonymized analytics to improve our product and your experience. To learn more, including how to turn off analytics, visit our dedicated documentation page: https://meilisearch.com/docs/learn/what_is_meilisearch/telemetry`

**Meilisearch version:**
NA

**Additional context**
If you prefer, you may want to use the `www` in the links: `https://www.meilisearch.com/docs` — the @meilisearch/docs-team has no preference.

Thanks ❤️

### PR DESCRIPTION
**Pull request by curquiza**
Completely fixes #3668

### CODE REVIEW

**Review by Kerollmops — APPROVED** [review]
Looks good to me 😊
I let you merge 🐡

**Comment by curquiza** [comment]
bors merge

**Comment by curquiza** [comment]
bors try

**Comment by curquiza** [comment]
bors merge

**Pull request merged**
