### PR TITLE
chore(http): rename task types

### LINKED ISSUE #1999: v0.25.0 RC: rename some task `type`
Following: https://github.com/meilisearch/specifications/pull/101
⚠️ Should be implemented once this PR is validated

We want to take the opportunity of v0.25.0 to fix some English mistakes in our API. We must rename
- `documentsAddition` into `documentAddition`
- `documentsPartial` into `documentPartial`
- `documentsDeletion` into `documentDeletion`

### PR DESCRIPTION
**Pull request by MarinPostma**
Rename
- documentsAddition into documentAddition
- documentsPartial into documentPartial
- documentsDeletion into documentDeletion

close #1999

### CODE REVIEW

**Review by curquiza — CHANGES_REQUESTED** [review]
The commits related to the CONTRIBUTING.md file should not be in this PR.

**Review by Kerollmops — CHANGES_REQUESTED** [review]
Don't you forget to rename the `TaskDetails` variants, too?

**Comment by MarinPostma** [comment]
@Kerollmops, the enum is untagged, but you're right, it's better for consistency.

**Review by curquiza — APPROVED** [review]

**Review by Kerollmops — APPROVED** [review]
Looks good to me!

**Comment by curquiza** [comment]
bors merge

**Pull request merged**
