### PR TITLE
Setup COMMIT_SHA and COMMIT_DATE build args in the Docker image

### PR DESCRIPTION
**Pull request by brunoocasali**
GitHub auto-closed my PR when I synced changes with my remote 🤷‍♂️  https://github.com/meilisearch/meilisearch/pull/2550
The last PR #3205 were closed to help @curquiza test the CI.

In any case, the summary of changes is quite similar:

- Fix `git` usage from my last attempt (when you use `actions/checkout`) you get the `git` command to use.
- Add the `build-args` definition from https://github.com/docker/build-push-action#inputs, which is supposed to work precisely as docker build `--build-arg`. 

Fixes https://github.com/meilisearch/meilisearch/issues/2028

The result will be like this:

image

### CODE REVIEW

**Comment by curquiza** [comment]
Let's watch this one now, old one is not relevant: https://github.com/meilisearch/meilisearch/actions/runs/3641684062

**Comment by brunoocasali** [comment]
I changed the name of the env vars this commit https://github.com/meilisearch/meilisearch/commit/a8c146fd13f6ce0c12967b3ef61f09237b804055 should have changed those environment variables as well :)

image

**Comment by curquiza** [comment]
Hey @brunoocasali 
I tested with `test-docker-ci-v2` but I got this (which is almost perfect)

Capture d’écran 2022-12-08 à 10 53 35

I would rather a different format of date, like the one we got when building the image locally

Capture d’écran 2022-12-08 à 10 53 15

Do you think it's possible?

**Comment by brunoocasali** [comment]
> Plus I cannot access the image you created (brunoocasali/meilisearch:v0.0.2-with-build-info)

I know that, I created this one manually to test if the `ENV` commands in the Dockerfile were ok :)

**Review by curquiza — APPROVED** [review]
It wooooooooorks 🎉 👏 

Capture d’écran 2022-12-08 à 16 50 54


Thanks for you help with this @brunoocasali!!!

bors merge

**Pull request merged**
