### PR TITLE
Optimize Prefixes and Merges

### PR DESCRIPTION
**Pull request by Kerollmops**
In this PR, we plan to optimize the read of LMDB to use read the entries in lexicographic order and better use the memory-mapping OS cache:

 - Optimize the prefix generation for word position docids (@manythefish)
 - Optimize the parallel merging of the caches to sort entries before merging the caches (@kerollmops)
 
## Benchmarks on 1cpu 2gb gpo3 (5k IOps)
 
Before on the tag meilisearch-v1.12.0-rc.3.

```
word_position_docids:merge_and_send_docids: 988s
compute_word_fst: 23.3s
word_pair_proximity_docids:merge_and_send_docids: 428s
compute_word_prefix_fid_docids:recompute_modified_prefixes: 76.3s
compute_word_prefix_position_docids:recompute_modified_prefixes:from_prefixes: 429s
```

After sorting the whole `HashMap`s in a `Vec` on this branch.

```
word_position_docids:merge_and_send_docids: 202s
compute_word_fst: 20.4s
word_pair_proximity_docids:merge_and_send_docids: 427s
compute_word_prefix_fid_docids:recompute_modified_prefixes: 65.5s
compute_word_prefix_position_docids:recompute_modified_prefixes:from_prefixes: 62.5s
```

### CODE REVIEW

**Comment by Kerollmops** [comment]
/bench workloads/hackernews-add-new-documents.json workloads/hackernews-modify-*

**Review by ManyTheFish — APPROVED** [review]

**Review by ManyTheFish — DISMISSED** [review]

**Comment by Kerollmops** [comment]
bors merge

**Comment by Kerollmops** [comment]
bors merge

**Comment by Kerollmops** [comment]
bors abort

I want to maybe change the name of the `merge_alt` function and perform more benchmarks on larger machines.

**Comment by Kerollmops** [comment]
bors cancel

**Review by ManyTheFish — APPROVED** [review]
bors merge

**Pull request merged**
