### PR TITLE
Fix display of http address

### PR DESCRIPTION
**Pull request by curquiza**
Wrong display introduced by https://github.com/meilisearch/MeiliSearch/pull/1206

Now displaying:

Capture d’écran 2021-03-26 à 12 04 59

### CODE REVIEW

**Review by MarinPostma — APPROVED** [review]
bors merge

**Comment by curquiza** [comment]
bors try

**Comment by curquiza** [comment]
Looks like this is mergeable now @MarinPostma 😄

**Comment by MarinPostma** [comment]
bors merge

**Pull request merged**
