### PR TITLE
Add a new link to the cloud pricing page

### PR DESCRIPTION
**Pull request by Kerollmops**
This PR promotes the Cloud by adding a link to the Pricing page to the startup message!

Capture d’écran 2023-06-29 à 17 40 22

### CODE REVIEW

**Review by macraig — APPROVED** [review]
🚀

**Review by gillian-meilisearch — APPROVED** [review]
👍🏻

**Comment by gillian-meilisearch** [comment]
bors merge

**Comment by gillian-meilisearch** [comment]
bors merge

**Comment by curquiza** [comment]
bors merge

**Pull request merged**
