### PR TITLE
Bump Milli to improve geosearch errors

### LINKED ISSUE #1734: Expecting error when using `_geoPoint` with `filter`
According to [the spec](https://github.com/meilisearch/specifications/blob/develop/text/0059-geo-search.md#post-search-indexesindexuidsearch):

> 🔴 Using `_geo`, `_geoDistance`, `_geoPoint` in a filter expression cause the API to return an invalid_filter error. `message` should be `:reservedKeyword is a reserved keyword and thus can't be used as a filter expression`.

When I send

```json
'{ "q": "Lille", "filter": "_geoDistance"  }'
```

or

```json
{ "q": "Lille", "filter": "_geoPoint(12.4, 14.6, 1)"  }
```

I don't get this error.

### PR DESCRIPTION
**Pull request by irevoire**
closes #1734 

@curquiza, your two examples still don't work because a filter must be composed of multiples operations; look at my screenshot to see what works and what doesn't.
Is this ok? :thinking: 

@gmourier,
What do you think?

image

And here is a screenshot with all the new errors that have been implemented

image

### CODE REVIEW

**Comment by curquiza** [comment]
It's ok for me. I used `geoPoint` as `geoRadius` is described in the spec, I mean without any `=`.
https://github.com/meilisearch/specifications/blob/develop/text/0059-geo-search.md#post-search-indexesindexuidsearch
But the behavior is ok for me

**Comment by irevoire** [comment]
Maybe we could define some `reserved_function` errors that are used alone without any operators and followed by parenthesis (`_geoRadius(...)` and `_geo(...)`).
And some `reserved_keywords` that are used as fields names (`_geoDistance` and `_geo`).
But personally, I would say this is enough for a first version :slightly_smiling_face:

**Comment by curquiza** [comment]
I agree, I think it's ok for a first version (if @gmourier is also ok with this of course)
Let's wait for the user feedback :)

**Review by curquiza — APPROVED** [review]
Check with @gmourier, it's ok!! 🎉 

bors merge

**Pull request merged**
