### PR TITLE
Keep only useful routes for /health

### LINKED ISSUE #379: [API] Health routes question
In the [route file](https://github.com/meilisearch/MeiliSearch/blob/master/meilisearch-http/src/routes/mod.rs):
```rust
// Private
    app.at("").nest(|router| {
        router
            .at("/health")
            .get(health::get_health)
            .post(health::set_healthy)
            .put(health::change_healthyness)
            .delete(health::set_unhealthy);
```
Do all these routes are necessary?
I say that only because we need to document them, so I want to know if we are going to keep all of them before doing it. 
Currently only `get` and `post` routes are documented.

Or maybe did we plan to delete all these routes because I can see the little `// Private` comment above them? :)

### PR DESCRIPTION
**Pull request by curquiza**
closes #379

### CODE REVIEW

**Comment by Kerollmops** [comment]
Ooops, don't you forgot to remove the associated functions? :)

**Comment by curquiza** [comment]
@Kerollmops, I checked that and I did not remove them because `set_healthy` and `set_unhealthy` are called in `change_healthyness`.

**Comment by Kerollmops** [comment]
Yay! good job! :)
Thank you, merging!

**Comment by bidoubiwa** [comment]
The documentation is already up to date with this change.

**Comment by bidoubiwa** [comment]
documentation: meilisearch/documentation#111

**Pull request merged**
