### PR TITLE
Return 201 on index creation

### LINKED ISSUE #1467: v0.21.0rc1 Post Index doesn't return the good http status code
**Describe the bug**
POST Index return `status: 200, statusMessage: "OK"`

**Expected behavior**
It should return `status: 201, statusMessage: "created"`

**Desktop:**
 - Version [0.21.0-rc1]

### PR DESCRIPTION
**Pull request by MarinPostma**
fix #1467

### CODE REVIEW

**Review by Kerollmops — DISMISSED** [review]
Thank you, easy enough to be merged now!
bors merge

**Comment by MarinPostma** [comment]
forgot to update the tests :facepalm:

**Review by alallema — COMMENTED** [review]
Thank you @MarinPostma!

**Review by Kerollmops — APPROVED** [review]
bors merge

**Comment by Kerollmops** [comment]
bors cancel

**Review by Kerollmops — APPROVED** [review]
bors merge

**Comment by MarinPostma** [comment]
bors merge

**Comment by irevoire** [comment]
bors merge

**Comment by irevoire** [comment]
bors merge

**Review by Kerollmops — APPROVED** [review]
bors merge

**Pull request merged**
