### PR TITLE
Bring back changes from v1.8.2 into v1.9.0

### PR DESCRIPTION
**Pull request by dureuill**

### CODE REVIEW

**Review by irevoire — DISMISSED** [review]
thanks!
bors merge

**Comment by irevoire** [comment]
bors cancel

**Comment by curquiza** [comment]
Merge into release-v1.9.0 to have the fix in v1.9.0 too, and not only in v1.8.3, not in v1.9.0, and then in v1.10.0 again ⚠️

**Review by curquiza — CHANGES_REQUESTED** [review]
👆

**Review by irevoire — APPROVED** [review]
perfect

bors merge

**Review by curquiza — APPROVED** [review]
bors merge

**Pull request merged**
