### PR TITLE
Enable the tests on windows in the CI

### LINKED ISSUE #1443: Add tests for Windows in CI
Our current CI that runs on each PR only runs tests for macos and ubuntu. We should run test on windows-latest
https://github.com/meilisearch/MeiliSearch/blob/main/.github/workflows/rust.yml

### PR DESCRIPTION
**Pull request by irevoire**
closes #1443

### CODE REVIEW

**Comment by irevoire** [comment]
@curquiza I was thinking; maybe we could also add the tests on rust nightly and beta like we did for milli?
What do you think?

**Comment by curquiza** [comment]
> @curquiza I was thinking; maybe we could also add the tests on rust nightly and beta like we did for milli?
What do you think?

I don't think this is relevant at the moment 🙂

**Comment by curquiza** [comment]
bors try

**Comment by curquiza** [comment]
bors try-

**Comment by curquiza** [comment]
bors try

**Review by curquiza — APPROVED** [review]
Awesome!!

bors merge

**Pull request merged**
