### PR TITLE
Make matches work with numerical value

### PR DESCRIPTION
**Pull request by Thearas**
# Pull Request

## What does this PR do?

Implement #1883.

I have test this PR with unit test. It appears to be working properly:
image

PTAL @curquiza 

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

### CODE REVIEW

**Comment by MarinPostma** [comment]
I find it weird that we partially highlight a number. I think a number should be considered as one word @gmourier @curquiza

**Comment by gmourier** [comment]
> I find it weird that we partially highlight a number. I think a number should be considered as one word @gmourier @curquiza

We should keep the same behavior as on a string where MeiliSearch does not match the whole word as well. The highlighting feature consists of having markers to guide the user's eye into the details. I'm not convinced by having different highlighting behaviors between "types" as the default behavior, I think it could create more confusion in the end than being really helpful.

On the other hand, we could give the possibility in the future to define the behavior of the highlighting feature e.g. `fully highlighted`, or even how each "type" could behave in case of partial highlighting.

**Review by curquiza — APPROVED** [review]
It works!

Thanks for the PR @Thearas 

⚠️ We need the @MarinPostma's review before any merge :)

**Comment by ManyTheFish** [comment]
Hello @Thearas @MarinPostma!

This PR should fix the issue, thanks!
However, we know that will not highlight numbers perfectly, mainly because of the behavior of our current tokenizer.
We don't have the time to enhance the tokenizer  before the beginning of 2022 and [an issue with the label `good first issue`](https://github.com/meilisearch/tokenizer/issues/62) has been opened for this.

thanks again for your contribution!

**Review by MarinPostma — APPROVED** [review]
thank you for your contribution :)

bors merge

**Pull request merged**
