### PR TITLE
Transplant the new search engine

### PR DESCRIPTION
**Pull request by curquiza**

### CODE REVIEW

**Comment by curquiza** [comment]
bors try

**Review by tpayet — APPROVED** [review]
lgtm 👍
ggwp

**Comment by tpayet** [comment]
bors merge

**Review by irevoire — APPROVED** [review]
I didn't run the code, but after reading the code I'm pretty sure this PR will not introduce any bugs.

**Review by Kerollmops — APPROVED** [review]
🧶

**Review by MarinPostma — APPROVED** [review]

**Pull request merged**
