### PR TITLE
fix wrong variant returned for invalid_api_key_indexes error

### LINKED ISSUE #2924: Wrong variant returned for `invalid_api_key_indexes` error when creating an API key.
> Sending a value that is not a valid index (e.g. regarding the index uid format) in the indexes field returns an [invalid_api_key_indexes](https://github.com/meilisearch/meilisearch/issues/0061-error-format-and-definitions.md#invalid_api_key_indexes) with a variant error message. See "Sending an invalid index uid format in indexes field" variant.

It should have been solved by https://github.com/meilisearch/meilisearch/issues/2158, but I did not get the new variant testing on the latest version.

```json
{
    "message": "`indexes` field value `[\"invalid index # / \\name with spaces\"]` is invalid. It should be an array of string representing index names.",
    "code": "invalid_api_key_indexes",
    "type": "invalid_request",
    "link": "https://docs.meilisearch.com/errors#invalid_api_key_indexes"
}
```

while I should receive

```json
{
    "message": "` [\"invalid index # / \\name with spaces\"]` is not a valid index uid. Index uid can be an integer or a string containing only alphanumeric characters, hyphens (-) and underscores (_).",
    "code": "invalid_api_key_indexes",
    "type": "invalid_request",
    "link": "https://docs.meilisearch.com/errors#invalid_api_key_indexes"
}
```

Relates to that catch-up specification https://github.com/meilisearch/specifications/pull/181 (The original one was never merged 🤔 So it makes me doubt if it was solved)

### PR DESCRIPTION
**Pull request by vishalsodani**
# Pull Request

## Related issue
Fixes #2924 

## What does this PR do?
- ...

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Comment by curquiza** [comment]
bors try

**Comment by curquiza** [comment]
bors try

**Review by ManyTheFish — APPROVED** [review]
Hello @vishalsodani, thank you for your contribution!
bors merge

**Comment by gmourier** [comment]
Hi everyone 👋

I just tested on `main` and looked at the code, the variant still doesn't seem to be the right one.

I'm still receiving 

```json
{
    "message": "`[\"&@----invalid\"]` is not a valid index uid. It should be an array of string representing index names.",
    "code": "invalid_api_key_indexes",
    "type": "invalid_request",
    "link": "https://docs.meilisearch.com/errors#invalid_api_key_indexes"
}
```

while the spec mentions

```json
{
    "message": "`[\"&@----invalid\"]` is not a valid index uid. Index uid can be an integer or a string containing only alphanumeric characters, hyphens (-) and underscores (_).",
    "code": "invalid_api_key_indexes",
    "type": "invalid_request",
    "link": "https://docs.meilisearch.com/errors#invalid_api_key_indexes"
}
```

**Pull request merged**
