### PR TITLE
Change the format of custom ranking rules when importing old dumps

### PR DESCRIPTION
**Pull request by Kerollmops**
This PR changes the format of the custom ranking rules from `asc(price)` to `title:asc` as the format changed between v0.21 and v0.22. The dumps are now correctly importing the custom ranking rules.

This PR also change the previous default ranking rules (without sort) to the new default ranking rules (with the new sort).

### CODE REVIEW

**Review by curquiza — APPROVED** [review]
Tested, it works!

**Review by MarinPostma — CHANGES_REQUESTED** [review]

**Review by curquiza — APPROVED** [review]

**Review by Kerollmops — COMMENTED** [review]
bors merge

**Review by curquiza — APPROVED** [review]
bors merge

**Review by MarinPostma — APPROVED** [review]
thanks!

**Pull request merged**
