### PR TITLE
auth tests

### PR DESCRIPTION
**Pull request by MarinPostma**
add regression tests on route authentication.

### CODE REVIEW

**Review by Kerollmops — APPROVED** [review]
Nice tests!
bors merge

**Review by irevoire — APPROVED** [review]
nice and concise :+1:

**Review by Kerollmops — APPROVED** [review]
bors merge

**Comment by irevoire** [comment]
bors merge

**Comment by MarinPostma** [comment]
bors merge

**Comment by Kerollmops** [comment]
bors merge

**Comment by irevoire** [comment]
bors merge

**Comment by irevoire** [comment]
bors merge 
BAD BORS :angry:

**Pull request merged**
