### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by Lioness100**
# Pull Request

## What does this PR do?
This PR fixes some typos throughout the repository (trial run for [a CLI I made](https://github.com/Lioness100/rspell)). I'm unfamiliar with this codebase, so if I broke anything that needs to be reverted, please let me know!

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Comment by irevoire** [comment]
Hey @Lioness100, you renamed an enum variant that broke the dumps.

**Review by Kerollmops — CHANGES_REQUESTED** [review]
Thank you very much for this PR. That's amazing!
Could you please change what I addressed? :)

**Comment by Lioness100** [comment]
Everything in those files should be reverted :)

**Review by Kerollmops — CHANGES_REQUESTED** [review]
Thank you very much. Could you rebase on main please?

**Comment by Lioness100** [comment]
Done!

**Comment by Kerollmops** [comment]
Hey @Lioness100,

Could you [install `cargo-insta`](https://crates.io/crates/cargo-insta) and run the following command to fix the tests? Changing typos changed our test files. Here is [the documentation of the insta tool](https://insta.rs/docs/cli/).

```bash
cargo insta test
cargo review
```

However, I am worried about these changes. Fixing typos is excellent, but we should probably have a CI check. We don't want to take that much time next time we fix them again. As you can see, there are now merge conflicts due to the time this PR took to be merged. What do you think?

**Comment by curquiza** [comment]
Hello @Lioness100 

can you rebase? the PR has multiple git conflicts, sorry for this 😥

**Comment by Lioness100** [comment]
Sorry @curquiza, I won't have time in the foreseeable future.

**Comment by curquiza** [comment]
@Lioness100 I completely understand. So I close the PR in the meantime. Feel free to reopen if you have more time in the future.
It's our bad, we were late on reviewing (because not critical so we un-prioritized it), sorry for the delay.

**Pull request closed without merging**
