### PR TITLE
Fix matching strategy error

### LINKED ISSUE #3391: When searching and using the matching strategy with a wrong value type we say « was expecting an object » while we’re actually expecting a string, this can be very confusing.

### PR DESCRIPTION
**Pull request by ManyTheFish**
# Pull Request

## Related issue
Fixes #3391

### CODE REVIEW

**Review by irevoire — DISMISSED** [review]
Noice thanks for the fix
bors merge

**Review by irevoire — APPROVED** [review]
Thanks² :crocodile: 
bors merge

**Comment by dureuill** [comment]
This PR needs https://github.com/meilisearch/meilisearch/pull/3395 for the tests to pass

**Review by irevoire — APPROVED** [review]
Nice, there is only a test left :joy: 
Thanks @ManyTheFish & @dureuill :oyster: 
bors merge

**Pull request merged**
