### PR TITLE
Feat(Analytics): Add analytics for search format options

### LINKED ISSUE #2308: Add telemetry for new cropping/highlight settings (v0.27.0)
Following https://github.com/meilisearch/specifications/commit/f5c6a8e183e22cc3b80d9a0251c411250f31674f we need to add telemetry for the new settings introduced in v0.27.0 for highlight and crop

Reminder: the telemetry can be disable at any moment using the `--no-analytics` flag when launching Meilisearch
```bash
meilisearch --no-analytics
```

### PR DESCRIPTION
**Pull request by ManyTheFish**
Specification: [#120](https://github.com/meilisearch/specifications/pull/120) ([f5c6a8e](https://github.com/meilisearch/specifications/commit/f5c6a8e183e22cc3b80d9a0251c411250f31674f))

fix #2308

### CODE REVIEW

**Comment by ManyTheFish** [comment]
@curquiza, should it be merged into the main branch or into a release branch?

**Review by irevoire — DISMISSED** [review]
:+1: Looks good to me!

**Comment by ManyTheFish** [comment]
bors merge

**Review by irevoire — APPROVED** [review]

**Comment by ManyTheFish** [comment]
bors merge

**Comment by irevoire** [comment]
pretty sure that's a flaky test
bors merge

**Pull request merged**
