### PR TITLE
Release v1.7.1

### PR DESCRIPTION
**Pull request by Kerollmops**
Bring the v1.7.1 changes back to main.

### CODE REVIEW

**Review by dureuill — APPROVED** [review]
☀️ 

bors merge

**Comment by curquiza** [comment]
⚠️ @Kerollmops and @dureuill for future merges: we never fix git conflict on a `release-v*` branch because when fixing git conflicts, you brought all commits from `main` into this branch, meaning we cannot use this branch for future releases (like v1.7.2)
You should follow this guide instead: https://github.com/meilisearch/engine-team/blob/main/resources/meilisearch-release.md#after-the-release-bring-back-changes-to-main

**Comment by dureuill** [comment]
woops, our bad curqui, I had missed that 😨

**Comment by curquiza** [comment]
Don't worry, Tamo noticed it before releasing v1.7.2, so we did not make any mistake in production, which is the most important 😊

**Pull request merged**
