### PR TITLE
Add Prometheus metrics to measure task queue latency

### PR DESCRIPTION
**Pull request by takaebato**
# Pull Request

## Related issue
Fixes https://github.com/meilisearch/meilisearch/issues/5046

## What does this PR do?

- Added Prometheus metrics to measure task queue latency

(Confirmed locally that latency is measured during parallel task execution in the benchmark.)

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Comment by takaebato** [comment]
I used a Gauge for the metric, but let me know if a Histogram or other metric type would be more appropriate!

**Review by irevoire — COMMENTED** [review]
Hey @takaebato,

That's awesome, could you also update the grafana dashboard we provide under [`assets/grafana-dashboard.json`](https://github.com/meilisearch/meilisearch/blob/main/assets/grafana-dashboard.json)

**Comment by takaebato** [comment]
@irevoire 

I updated the grafana dashboard! https://github.com/meilisearch/meilisearch/pull/5178/commits/195785c47f1f528443f92674814e7ed5063ad6a8
I'd appreciate any suggestions or feedback!

スクリーンショット 2024-12-27 23 22 32

**Review by irevoire — APPROVED** [review]
Awesome @takaebato, that's perfect thanks a lot for your contribution :fire: 

bors merge

**Pull request merged**
