### PR TITLE
Bring back changes from release-v0.30.3 to main

### PR DESCRIPTION
**Pull request by curquiza**
⚠️ ⚠️ I had to fix git conflicts, ensure I did not lose anything ⚠️ ⚠️

### CODE REVIEW

**Review by Kerollmops — DISMISSED** [review]
It looks ok to me, but I would prefer @irevoire to take a look as he is the author here.

**Comment by curquiza** [comment]
@Kerollmops the tests are failing, I guess it's related to the new name of `dumps_dir`, but I don't know how to fix it properly.
```
a field with a similar name exists: `dump_dir`
```
Maybe @dureuill could help us and ensure my PR will not break what you did by solving this https://github.com/meilisearch/meilisearch/issues/3132

**Comment by dureuill** [comment]
Pushed a commit to fix the build.

**Review by Kerollmops — APPROVED** [review]
I am waiting for @irevoire's review here!

**Review by irevoire — APPROVED** [review]
I checked & tested the dump import thingy and it works thus we should be good to merge+release :+1:

**Comment by curquiza** [comment]
bors merge

**Pull request merged**
