### PR TITLE
Add version flag

### LINKED ISSUE #2315: (Re)Introduce the `--version` flag on the Rust binary
I am not sure how we lost that, where the `--version`/`-v` flag goes but I am sure we had one. We must reintroduce it.

I downloaded the binary by using [the quick start guide and cURL](https://docs.meilisearch.com/learn/getting_started/quick_start.html#local-installation) and I was astonished to see that there was no way to know the version of the binary without directly running it. Even the `--help` option isn't giving us any more information. I downloaded the v0.26.1 version.

```
./meilisearch --version
error: Found argument '--version' which wasn't expected, or isn't valid in this context

	If you tried to supply `--version` as a value rather than a flag, use `-- --version`

USAGE:
    meilisearch [OPTIONS]

For more information try --help
```

```
./meilisearch -v
error: Found argument '-v' which wasn't expected, or isn't valid in this context

	If you tried to supply `-v` as a value rather than a flag, use `-- -v`

USAGE:
    meilisearch [OPTIONS]

For more information try --help
```

### PR DESCRIPTION
**Pull request by sanders41**
# Pull Request

## What does this PR do?
Fixes #2315

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Review by MarinPostma — DISMISSED** [review]
well done!

**Review by Kerollmops — DISMISSED** [review]
It works great on my side! Thank you!
Unfortunately, we have a Clippy bug here...

bors merge

**Comment by Kerollmops** [comment]
For your information @curquiza , I moved this PR to the _release-v0.27_ branch as we want it in the next release!

**Comment by curquiza** [comment]
I've added it to the Milestones, can you re-approve it? :)

**Comment by curquiza** [comment]
And thanks a lot @sanders41 for the PR 🚀

**Review by Kerollmops — APPROVED** [review]
Reapproving, I hope the Clippy issue will not happen!
bors merge

**Pull request merged**
