### PR TITLE
change ubuntu version

### PR DESCRIPTION
**Pull request by MarinPostma**
Change the CI ubuntu version from `latest` to `18.04` because `latest` uses a too recent version of glibc, preventing meilisearch from running on the debian version of the DO image

### CODE REVIEW

**Comment by MarinPostma** [comment]
bors try

**Comment by MarinPostma** [comment]
bors try

**Comment by MarinPostma** [comment]
bors try-

**Comment by MarinPostma** [comment]
bors try

**Comment by MarinPostma** [comment]
bors try-

**Comment by MarinPostma** [comment]
borst try

**Comment by MarinPostma** [comment]
bors try

**Review by curquiza — APPROVED** [review]

**Comment by MarinPostma** [comment]
bors merge

**Pull request merged**
