### PR TITLE
Fix metrics feature

### PR DESCRIPTION
**Pull request by james-2001**
# Pull Request

## Related issue

Resolves: #3469
See also: #2763

## What does this PR do?
As reported the metrics feature was broken by still using and old reference to `meilisearch_auth::actions`. This commit switches to the new location, `meilisearch_types::keys::actions`.

The original issue was not *that* clear as to exactly what was broken, and the build logs have disappeared, but it seemed to just be this one line fix. If this is not the case and I've missed the mark let me know, and i'll head back to the drawing board.

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

### CODE REVIEW

**Comment by irevoire** [comment]
Hey @james-2001, I tried to `cargo check --features metrics`, and it looks like your PR is not finished yet.
I’m going to put the PR in draft mode until you finish it!
Don’t hesitate to ping me / put back the PR in a normal state once you think it’s ready 😁 

And thanks for your contribution ❤️

**Comment by james-2001** [comment]
Lets have another go :smile: Now building with `--features metrics` and then running with `--enable-metrics-route` provides a metrics endpoint with prometheus-looking logs, e.g. 
```
 HELP http_requests_total HTTP requests total
# TYPE http_requests_total counter
http_requests_total{method="GET",path="/"} 1
http_requests_total{method="GET",path="/fonts/Work_Sans/light.woff2"} 1
http_requests_total{method="GET",path="/fonts/Work_Sans/medium.woff2"} 1
http_requests_total{method="GET",path="/fonts/Work_Sans/regular.woff2"} 1
http_requests_total{method="GET",path="/indexes"} 1
http_requests_total{method="GET",path="/manifest.json"} 1
http_requests_total{method="GET",path="/metrics"} 1
```

and etc

**Review by irevoire — CHANGES_REQUESTED** [review]
Hey, one last change, you need to add a bunch of feature flags when initializing the opt struct in the tests

**Comment by james-2001** [comment]
Not sure I quite follow you here. As far as I can see, the `Opt` structs in the tests are all initialised through `default_settings` in `tests/common/server.rs`, which already initialises `enable_metrics_route` under a metrics flag. I have added a flag in `segment_analytics.rs` that was causing the builds to fail; was this what you meant?

**Review by irevoire — APPROVED** [review]
Perfect! Thanks @james-2001 🎡 
bors merge

**Review by irevoire — APPROVED** [review]
Thanks for the quick fix

bors merge

**Pull request merged**
