### PR TITLE
add version guard in copy_and_compact_to_path function

### LINKED ISSUE #958: Impossible to load snapshot
## Steps

In an empty directory only containing the MeiliSearch binary (v0.14.0)

1. I launch MeiliSearch with a snapshot creation every 10 secondes

```bash
$ ./meilisearch --snapshot-path mySnapShots/ --snapshot-interval-sec 10
```

2. I create an index and I add documents. But the bug is also present even if I do not do any action with MeiliSearch.

3. After one snapshot was created, I stop MeiliSearch. Two folders are present: `data.ms` and `mySnapShots/` (containing `data.ms.tar.gz`)

4. I try to launch MeiliSearch with the snapshot:
```bash
$ ./meilisearch --load-from-snapshot mySnapShots/data.ms.tar.gz
Error: database already exists at "./data.ms"
```

=> the error is expected [according to the docs](https://docs.meilisearch.com/guides/advanced_guides/safeguards.html#start-from-snapshot).

5. So I remove `data.ms`

6. I re-launch MeiliSearch with the same command:
```bash
$ ./meilisearch --load-from-snapshot mySnapShots/data.ms.tar.gz
Error: Cannot open database, expected MeiliSearch engine version: <0.12.0, current engine version: 0.14.0
```
=> a `data.ms` is now present in my folder.
=> **the error is not expected**.

7. If I try to use the `--ignore-snapshot-if-db-exists` flag:

```bash
./meilisearch --load-from-snapshot mySnapShots/data.ms.tar.gz --ignore-snapshot-if-db-exists
error: The argument '--ignore-snapshot-if-db-exists <ignore-snapshot-if-db-exists>' requires a value but none was supplied

USAGE:
    meilisearch --db-path <db-path> --env <env> --http-addr <http-addr> --http-payload-size-limit <http-payload-size-limit> --ignore-snapshot-if-db-exists <ignore-snapshot-if-db-exists> --load-from-snapshot <load-from-snapshot> --max-mdb-size <max-mdb-size> --max-udb-size <max-udb-size> --no-analytics <no-analytics> --sentry-dsn <sentry-dsn>

For more information try --help
```

=> **This flag should not expect any value**.

## Version

MeiliSearch v0.14.0

## Fix

It should be a hotfix with a `v0.14.1` since the snapshots are not usable right now (If I used them correctly)

### PR DESCRIPTION
**Pull request by LegendreM**
fix #958

need to create 0.14.1

### CODE REVIEW

**Review by curquiza — COMMENTED** [review]
I still got this:

```bash
$ cargo run --release -- --load-from-snapshot mySnapShots/data.ms.tar.gz --ignore-snapshot-if-db-exists
    Finished release [optimized + debuginfo] target(s) in 0.20s
     Running `target/release/meilisearch --load-from-snapshot mySnapShots/data.ms.tar.gz --ignore-snapshot-if-db-exists`
error: The argument '--ignore-snapshot-if-db-exists <ignore-snapshot-if-db-exists>' requires a value but none was supplied

USAGE:
    meilisearch --db-path <db-path> --env <env> --http-addr <http-addr> --http-payload-size-limit <http-payload-size-limit> --ignore-snapshot-if-db-exists <ignore-snapshot-if-db-exists> --load-from-snapshot <load-from-snapshot> --max-mdb-size <max-mdb-size> --max-udb-size <max-udb-size> --no-analytics <no-analytics> --sentry-dsn <sentry-dsn>

For more information try --help
```

Is this normal? Should this PR fix it?

**Comment by MarinPostma** [comment]
@curquiza Yeah just found that one out, it looks like a bug with structopt, I'm opening a issue on their repo. In the meantime, you can stilll use the flags, but you have to pass the value `true` for each flag.

**Review by MarinPostma — APPROVED** [review]
bors r+

**Comment by curquiza** [comment]
@MarinPostma #958 described this bug with the flag, that's why I asked.

**Pull request merged**
