### PR TITLE
Fix dump v1 (attributesForFaceting, and criteria)

### LINKED ISSUE #1553: Dumps pre v0.21 aren't working on v0.21.0rc3
**Describe the bug**
I got an error trying to import a bump into v0.21rc3
Tries both on docker image and compiled from source

**To Reproduce**
1. Create a dump with an older version of MeiliSearch (in my case it's a v0.18.1 dump)
2. Launch MeiliSearch v0.21.0rc3 with the --import-dump path/to/dump option
3. Error returned: 

```
[2021-08-03T17:01:05Z INFO  meilisearch_http::index_controller::dump_actor::loaders::v1] Loading dump, dump database version: 0.18.1, dump version: V1
Error: unknown field `attributesForFaceting`, expected one of `rankingRules`, `distinctAttribute`, `searchableAttributes`, `displayedAttributes`, `stopWords`, `synonyms`, `filterableAttributes` at line 1 column 220
```

**Expected behavior**
The dump should be imported without errors

**MeiliSearch version:** 
v0.21.0rc3

### PR DESCRIPTION
**Pull request by MarinPostma**
close #1553

### CODE REVIEW

**Comment by MarinPostma** [comment]
@CaroFG can you confirm me that it works with your dump?

**Review by curquiza — CHANGES_REQUESTED** [review]
```
[2021-08-04T13:53:22Z WARN  meilisearch_http::index_controller::dump_actor::loaders::v1] The criteria `words` and `wordsPosition` have been merged into a single criterion `words` so `wordsPositon` will be ignored`

```
should be

```
[2021-08-04T13:53:22Z WARN  meilisearch_http::index_controller::dump_actor::loaders::v1] The criteria `attribute` and `wordsPosition` have been merged into a single criterion `attribute` so `wordsPositon` will be ignored
```

**Comment by CaroFG** [comment]
It works! 😁

**Review by curquiza — APPROVED** [review]
LGTM! 👌

**Comment by MarinPostma** [comment]
bors merge

**Review by curquiza — APPROVED** [review]
perfect!

bors merge

**Comment by curquiza** [comment]
bors merge

**Comment by curquiza** [comment]
Bors merge

**Pull request merged**
