### PR TITLE
Fix api keys bugs

### LINKED ISSUE #2730: v0.29.0 wildcards in key actions does not seem to work properly
**Describe the bug**
For example the wildcard `documents.*` does not work to create documents, while `documents.create` does.

**To Reproduce**
1. Create a key with `actions: ['documents.*']
2. Use this key to add documents
3. `invalid_api_key`

**Expected behavior**
Should be able to add documents

**Screenshots**
/

**Meilisearch version:** 
v.0.29.1

If you have time, is it possible to add [additional tests](https://github.com/meilisearch/meilisearch/blob/01a47e2db51815e375be699bca6153ca98f0e6a8/meilisearch-http/tests/auth/api_keys.rs) to ensure this behavior is working?

### LINKED ISSUE #2731: v0.29.1 recieving a throw on get task when fetching a task of an index creation
**Describe the bug**

When I dont have the rights to create a specific key, but I create it anyway, the returned taskUid is considered not existing.

The task of the index creation is the following 

Key: 

```js
      const key = await client.createKey({
        uid,
        description: 'Indexing Products API key',
        actions: ['indexes.*', 'tasks.*'],
        indexes: ['index_1'],
        expiresAt: null,
      })
```

```js
      const newClient = new MeiliSearch({ host: HOST, apiKey: key.key })
      const taskInfo = await newClient.createIndex('indexes_wildcards')
```

Returned task
```
   {
      taskInfo: {
        taskUid: 3758,
        indexUid: 'indexes_wildcards',
        status: 'enqueued',
        type: 'indexCreation',
        enqueuedAt: '2022-09-01T11:12:33.610232Z'
      }
    }
```

When making a query on 
```
GET /tasks/3758
```

I receive the following error: 

```
Task `3758` not found.
```

Meilisearch log

```
[2022-09-01T11:16:20Z INFO  actix_web::middleware::logger] 127.0.0.1 "GET /tasks/3758 HTTP/1.1" 404 142 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.000211
```

**To Reproduce**
- Create an index on which the key has no right
- Fetch task that was returned by the index creation route
- Error, the task does not exists

**Expected behavior**
No provided task uid should be not found.

**Meilisearch version:** 
v0.29.1

### PR DESCRIPTION
**Pull request by ManyTheFish**
fixes #2730 (fixed by [234efaf](https://github.com/meilisearch/meilisearch/pull/2734/commits/234efaf6fbaa43d458b14a099e25b9fe377c95b0))
fixes #2731 (fixed by [2fcfe62](https://github.com/meilisearch/meilisearch/pull/2734/commits/2fcfe62b19a28d218dc17636b9bbcca8cbbf3d0a))

### CODE REVIEW

**Review by Kerollmops — APPROVED** [review]
LGTM, thank you!
bors merge

**Comment by ManyTheFish** [comment]
bors merge

**Review by Kerollmops — CHANGES_REQUESTED** [review]
Could you please rebase, last time it fixed the Github CI issue?

**Review by Kerollmops — APPROVED** [review]
bors merge

**Comment by curquiza** [comment]
bors merge

**Comment by curquiza** [comment]
Merge by hand since we don't know why it fails with bors!

**Pull request merged**
