### PR TITLE
Fix phrase search containing stop words

### PR DESCRIPTION
**Pull request by ManyTheFish**
# Summary
A search with a phrase containing only stop words was returning an HTTP error 500,
this PR filters the phrase containing only stop words dropping them before the search starts, a query with a phrase containing only stop words now behaves like a placeholder search.

fixes https://github.com/meilisearch/meilisearch/issues/3521

related v1.0.2 PR on milli: https://github.com/meilisearch/milli/pull/779

### CODE REVIEW

**Comment by curquiza** [comment]
@ManyTheFish can we merge this? 😊

**Comment by ManyTheFish** [comment]
@curquiza yes we will merge this for v1.1.0

**Review by dureuill — APPROVED** [review]
Thank you! I approve this PR since similar code was approved by @irevoire for v1.0.2.

Should we directly address the panicking dereference in `matching_words.rs`? We could either add explicit handling of the case where the vec is empty at that point, or, if that doesn't make sense, add some documentation on the `MatchingWords` structure and `MatchingWords::new` function stating the precondition on the input `Vec<(Vec<Rc<MatchingWord>>` (each inner vec contains at least one element).

What do you think?

**Comment by ManyTheFish** [comment]
Hello @dureuill, I think this will not occur anymore, however, to be 100% safe, I can change the code!

Let me know, I'll follow your suggestion.

**Comment by dureuill** [comment]
> I think this will not occur anymore

That's great! I think we can do either of:

 1. keep the panic behavior with some documentation on the precondition of the `MatchingWords` structure:
   ```rust
  impl MatchingWords {
      /// Constructs a `MatchingWords` container from its inner structure.
      ///
      /// # Panics
      ///
      /// - If any of the inner vectors in `matching_words` is empty.
      pub fn new(mut matching_words: Vec<(Vec<Rc<MatchingWord>>, Vec<PrimitiveWordId>)>) -> Self {
  ```

   Then ideally we'd also document above the calls to `MatchingWords::new` why none of the vecs are empty. 
   
 2. let the callers handle the precondition by changing the return value of `MatchingWords::new` to an `Option<Self>`:
 ```rust
     /// Constructs a `MatchingWords` container from its inner structure.
    ///
    /// Returns `None` if any of the inner vectors in `matching_words` is empty.
    pub fn new(mut matching_words: Vec<(Vec<Rc<MatchingWord>>, Vec<PrimitiveWordId>)>) -> Option<Self> {
```

In this second option we'd need to update the callers to handle the option, either to pass up the `None` further, or to `unwrap` it with a comment explaining why the precondition holds (unless it is already established from context).

**Review by dureuill — COMMENTED** [review]
@ManyTheFish 

OK, I'm unsure which is better between failing-fast like before or filtering non-sensical inputs like now. If going this third route, I suggested using `retain` rather than a new `Vec` to spare the allocation.

**Comment by ManyTheFish** [comment]
Hello @dureuill, I took into account your last comment, we are now returning an internal error in the case of the MatchingWord creation fails.

**Review by dureuill — APPROVED** [review]
Hello @ManyTheFish!

Thanks for the changes! 

In general, I'd say that for errors that "should never happen" eg programming errors, we could prefer panicking to `InternalError`s, so as to not create "dead code".

However, I'm not really aware of what our policy is wrt `InternalError` vs `panic`s so I trust that you chose the solution that is in line with the current policy. Thank you again 😃

**Comment by ManyTheFish** [comment]
@dureuill, In an ideal world, I'd say that an internal error should never happen, therefore, if an internal error appears, we expect the user to create an issue referenced as a bug. So from my POV, it seems legitimate that an internal error is thrown in this case.
thank you for your review!

bors merge

**Pull request merged**
