### PR TITLE
Add Cargo feature for LMDB's POSIX semaphores

### PR DESCRIPTION
**Pull request by GregoryConrad**
See https://github.com/meilisearch/milli/pull/757

### CODE REVIEW

**Comment by GregoryConrad** [comment]
Also, not sure if this PR should be made to `main` or not; did I choose the correct branch?

**Comment by irevoire** [comment]
Hey @GregoryConrad, we're currently moving milli to the meilisearch repository to reduce the time we spent in useless synchronisation between both repo.
Thus, it would be better to open your pr on meilisearch -- main 👍

**Comment by GregoryConrad** [comment]
Great; I noticed there was a `release-v1.0.0` branch and wasn't sure if this PR should be made there instead.

**Comment by irevoire** [comment]
Yeah, our workflow work as-is;
-> During one month, we're in the sprint phase and implement new features for the next release of meilisearch. During this time we push & merge on main
-> Once this is over we enter the pre-release phase, it last one month as well, during this time we merge ~only bug fixes required for the next release in `release-v1.x.0`

So, since your change is not required for the next release it would go in meilisearch -- main 👍

**Comment by dureuill** [comment]
Hey @GregoryConrad :wave: thanks for your work on this :-)

Questions to whom it may concern on the team:

1. should this be a feature flag at the milli level, or should we just always enable/disable this flag at the milli level? 
2. If we want a flag for milli, same question for meilisearch itself.

More generally, what are the advantages/drawbacks of using POSIX semaphores on macOS? I seem to remember off the top of my head:

- The number of POSIX semaphores is not limited to 10 like the number of sysv semaphores, fixing some of the os errors we sometimes get in tests under macOS (something we could consider for milli/meilisearch tests under macOS)
- As OP noted, only POSIX semaphores are supported when using App Sandbox
- POSIX semaphores only provide "filesystem persistence" rather than "process persistence" like sysv semaphores. What this means is that if milli crashes in an *impromptu* manner, then the semaphore won't be released, which in the case of LMDB if my understanding is correct could result in meilisearch believing that the DB is locked by another process when it actually is not. In Meilisearch we could probably work around this by ignoring the lock (since the same DB is not supposed to be used by multiple concurrent instances just yet) or by asking the user to release the lock by deleting the lock file, but both workarounds add a new failure mode
- I have no idea of whether the performance characteristics of both kinds of semaphores are similar or not

Is the above correct, and am I missing something?

**Comment by GregoryConrad** [comment]
Hi!

> 1. should this be a feature flag at the milli level, or should we just always enable/disable this flag at the milli level?

It really is just a `heed` feature, but due to how Cargo dependencies work, you can't reliably set a feature on a transitive dependency so it also needs to be exposed in milli.

I suppose the `build.rs` implementation over in `lmdb-master-sys` could instead check the binary target directly and enable/disable, but I think we should still leave it up to the end-user who is compiling the binary. There are use cases where you may want to use POSIX semaphores on linux and not SysV (which would probably be the default).

> 2. If we want a flag for milli, same question for meilisearch itself.

Maybe. My use case for this Cargo feature was compiling to macOS and iOS applications. It could work well for Linux targets as well, at least when building containers. That is something you could benchmark in meilisearch and see if it's worth it. I.e., POSIX semaphores provide a slight speed improvement over SysV semaphores at the cost of possibly leaking the semaphore in the event of a crash. However, if dealing with a container, the container would simply restart and any semaphore should be released. Now, this speed improvement (if there is even a noticeable one in benchmarks) might not even be worth changing the build scripts you have; it is likely bottlenecks are elsewhere and not in something as mundane as a semaphore difference.

> More generally, what are the advantages/drawbacks of using POSIX semaphores on macOS? I seem to remember off the top of my head:

You got all of the ones I am aware of. I will note though that SysV semaphores require more overhead and are more complex than POSIX semaphores, and consequently tend to be slower (not sure by what margin).

**Review by dureuill — APPROVED** [review]
Thanks for your answers! 

We can consider using POSIX semaphores in Meilisearch independently from this PR. It looks good to me.

bors merge

**Comment by dureuill** [comment]
ubuntu mirrors are not feeling well today :/

let's try again

bors merge

**Comment by dureuill** [comment]
How is Ubuntu faring today?

bors merge

**Pull request merged**
