### PR TITLE
Update insta snap tests for index dates of dump v5

### PR DESCRIPTION
**Pull request by loiclec**
This PR simply updates the content of the insta snapshot test following https://github.com/meilisearch/meilisearch/pull/3013 . I manually verified that the dates in the snaps are indeed correct.

### CODE REVIEW

**Review by dureuill — DISMISSED** [review]
This looks good to me, especially as you checked the dates manually!

**Review by Kerollmops — DISMISSED** [review]
I like this too!

**Comment by loiclec** [comment]
oh, wait before merging, I forgot one place where the tests should be updated as well :)

**Review by Kerollmops — APPROVED** [review]
I like this too and again!

**Comment by loiclec** [comment]
bors merge

**Comment by dureuill** [comment]
We need to set a milestone for the PR to pass all checks. I did so on this PR.

**Comment by curquiza** [comment]
bors merge

**Pull request merged**
