### PR TITLE
Updated messages pointing to the docs website

### LINKED ISSUE #3668: Update messages pointing to the docs website
**Describe the bug**
The new documentation website changed its URL from https://docs.meilisearch.com to https://meilisearch.com/docs. Additionally, we have dropped `.html` extensions from all our links.

These two changes should be reflected in any messages referencing the docs site.

**To Reproduce**
For example, when a user launches `meilisearch`, the welcome message includes this paragraph:

`We collect anonymized analytics to improve our product and your experience. To learn more, including how to turn off analytics, visit our dedicated documentation page: https://docs.meilisearch.com/learn/what_is_meilisearch/telemetry.html`

I'm sure there are many others across the codebase that I'm not immediately aware of.

**Expected behavior**
The updated launch message should look something like this:

`We collect anonymized analytics to improve our product and your experience. To learn more, including how to turn off analytics, visit our dedicated documentation page: https://meilisearch.com/docs/learn/what_is_meilisearch/telemetry`

**Meilisearch version:**
NA

**Additional context**
If you prefer, you may want to use the `www` in the links: `https://www.meilisearch.com/docs` — the @meilisearch/docs-team has no preference.

Thanks ❤️

### PR DESCRIPTION
**Pull request by roy9495**
# Pull Request

Fixes partially #3668

## What does this PR do?
- ...Any messages referencing this docs site https://docs.meilisearch.com has been changed to this docs site https://meilisearch.com/docs .
 Thanks.

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Review by curquiza — APPROVED** [review]
Some links are missing, but since we need to release this by the end of the week, I want to move forward

thanks for your work @roy9495 

bors merge

**Comment by curquiza** [comment]
bors merge

**Comment by curquiza** [comment]
bors merge-

**Comment by curquiza** [comment]
bors merge

**Comment by roy9495** [comment]
Thank you

**Pull request merged**
