### PR TITLE
Add more integrations to SDK CI

### PR DESCRIPTION
**Pull request by curquiza**
For the integration scope management, but also to anticipate bugs and breaking changes for engine team, we need to add more SDKs tests into the CI

### CODE REVIEW

**Review by brunoocasali — APPROVED** [review]
LGTM!!! 🎉

**Comment by curquiza** [comment]
bors merge

**Comment by curquiza** [comment]
Bors merge

**Comment by brunoocasali** [comment]
bors merge

**Comment by curquiza** [comment]
bors merge

**Comment by curquiza** [comment]
bors merge

**Pull request merged**
