### PR TITLE
Update README.md for contributions

### PR DESCRIPTION
**Pull request by curquiza**

### CODE REVIEW

**Review by tpayet — APPROVED** [review]
awesome!

**Comment by curquiza** [comment]
Thanks! bors merge

**Comment by curquiza** [comment]
bors merge

**Comment by curquiza** [comment]
Oh yes... we should merge #1319 before this PR...

**Comment by curquiza** [comment]
bors merge

**Comment by curquiza** [comment]
bors try

**Review by MarinPostma — APPROVED** [review]

**Comment by MarinPostma** [comment]
bors merge

**Pull request merged**
