### PR TITLE
Uncomment cache steps in Github CI

### LINKED ISSUE #2864: Cache in GitHub CI - temporarelly commented
We had weird issue with our CI to be able to merge our PR:

Capture d’écran 2022-10-06 à 15 14 24

[Detailed logs](https://github.com/meilisearch/meilisearch/actions/runs/3196622099/jobs/5218796961) (will disappear in 90 days)

To fix this, we had to comment the job steps about the cache: https://github.com/meilisearch/meilisearch/pull/2862/commits/ab17c0acd570eb3c917b7c98c984a84bea070115

I currently don't know where this issue comes from, especially it only happens when using bors.

If someone has a clue, please let us know. So far, we let the steps commented, but the goal is to use the cache again.

### PR DESCRIPTION
**Pull request by AM1TB**
# Pull Request

Uncomment cache steps as they were previously affected by an issue with Github actions: https://www.githubstatus.com/incidents/gq1x0j8bv67v

## Related issue
Fixes #2864 

## What does this PR do?
- Reintroduce the rust-cache steps within Github CI.

## PR checklist
Please check if your PR fulfills the following requirements:
- [X] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [X] Have you read the contributing guidelines?
- [X] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Comment by AM1TB** [comment]
@curquiza pl help with running the workflows on this to test if the cache steps are working.

**Comment by curquiza** [comment]
bors try

**Review by curquiza — APPROVED** [review]
Thanks @AM1TB

**Comment by curquiza** [comment]
bors merge

**Pull request merged**
