### PR TITLE
Add image source label to dockerfiles

### PR DESCRIPTION
**Pull request by wuast94**
To get changelogs shown with Renovate a docker container has to add the source label described in the OCI Image Format Specification.

For reference: https://github.com/renovatebot/renovate/blob/main/lib/modules/datasource/docker/readme.md

### CODE REVIEW

**Comment by curquiza** [comment]
Hello @wuast94 
Sorry, we are not interested in Renovate so far

I close this PR, but thanks for the suggestion 😊 We will re-open this PR if we change our mind

**Comment by wuast94** [comment]
@curquiza its not to add renovate here, its so that repos that run renovate like mine can show the release notes. i run renovate on my repo to make pull requests on new versions.

**Comment by curquiza** [comment]
My baaaad, I just understood, I went too fast. Reopening and merging

**Review by curquiza — APPROVED** [review]
bors merge

**Comment by curquiza** [comment]
bors merge

**Pull request merged**
