### PR TITLE
Fix bug where search with distinct attribute and no ranking, returns offset+limit hits

### LINKED ISSUE #4078: Search with distinctAttribute returns offset+limit hits
Describe the bug
Search with distinctAttribute and non-zero offset returns `offset+limit` hits, instead of `limit`. 

To Reproduce
Make an index with `distinctAttribute`,  without `ranking_rules`. 
Add 40 documents with 20 distinct attribute values.
Empty search request, only limit=10, offset=20.

Expected behavior
10 hits, same as `limit`

Actual behavioir
30 hits, actually `offset+limit`

Screenshots

Meilisearch version:
1.3.5

Additional context
Looks like a bug in bucket_sort.rs - `results` contains matches max size `limit+offset`, and there's no drop first `offset` matches. 

https://github.com/meilisearch/meilisearch/blob/bb79bdb3f8e04afdc531ea663b93c47317b118c9/milli/src/search/new/bucket_sort.rs#L48-L65

### PR DESCRIPTION
**Pull request by vivek-26**
# Pull Request

## Related issue
Fixes #4078 

## What does this PR do?
This PR - 
- Fixes bug where search with distinct attribute and no ranking, returns offset+limit hits.
- Adds unit and integration tests.

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Review by ManyTheFish — DISMISSED** [review]
Hello @vivek-26,
this PR looks good to me thank you for your contribution,
we would like to release your work in a patch release, could you rebase on `release-v1.4.1`, please?

Thank you again!

**Review by Kerollmops — CHANGES_REQUESTED** [review]
Hey @vivek-26 👋

Thank you for the PR, it's valid and perfectly fixes the issue. However, it seems that your original PR is only 3 commits, right? would it be possible to cherry-pick them on your branch, please?

```bash
git checkout bug/search_distinct_attribute_no_ranking
# Reset your branch to start from scratch from the release branch
git reset --hard release-v1.4.1

# Apply your commits one by one
# You'll probably have to fix some conflicts...
git cherry-pick 6e8518a
git cherry-pick d32e756
git cherry-pick a76b7b3

# Push your changes
git push --force
```

**Review by Kerollmops — APPROVED** [review]
That's perfect thank you 🧀
bors merge

**Review by curquiza — APPROVED** [review]
bors merge

**Pull request merged**
