### PR TITLE
Add error message for invalid task status

### LINKED ISSUE #2940: `invalid_task_status` is never raised on `GET /tasks`
**Describe the bug**

Sending an inexistent status returns a `bad_request` error while it should be `invalid_task_status`.

**To reproduce**

`curl 'http://127.0.0.1:7700/tasks?status=1`

```json
{
    "message": "Query deserialize error: invalid task status `1`, expecting one of: enqueued, processing, succeeded, or failed",
    "code": "bad_request",
    "type": "invalid_request",
    "link": "https://docs.meilisearch.com/errors#bad_request"
}
```

**Expected behavior**
[A clear and concise description of what you expected to happen.](https://github.com/meilisearch/specifications/blob/main/text/0061-error-format-and-definitions.md#invalid_task_status)

```json
{
    "message": "Task status `:status` is invalid. Available task status are: `:taskStatuses`.",
    "code": "invalid_task_status",
    "type": "invalid_request",
    "link":"https://docs.meilisearch.com/errors#invalid_task_status"
}
```

**Meilisearch version:** [e.g. v0.29.1]

### PR DESCRIPTION
**Pull request by shogohida**
# Pull Request

## Related issue
Fixes #2940 

## What does this PR do?
- Makes Meilisearch show a correct error message for invalid task status as [this page](https://github.com/meilisearch/specifications/blob/main/text/0061-error-format-and-definitions.md#invalid_task_status) shows

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Comment by curquiza** [comment]
Hello @shogohida 

Thanks for the PR!

Is your PR finished? I see you opened a draft PR and not a "ready to review" one. Let us know when yo have finished

Also, I see there is an issue with the `Rustfmt` test, can you fix this?

Thanks for your contribution 🙏

**Comment by curquiza** [comment]
bors try

**Comment by shogohida** [comment]
@curquiza 
Thanks for your comment! I fixed the issue of `Rustfmt` so I decided to open the pull request.

As I commented [here](https://github.com/meilisearch/meilisearch/issues/2939#issuecomment-1288128015), I'm still stuck to get a correct error message... I haven't written any tests yet due to that.

It seems it's because ResponseError is used to generate the message [here](https://github.com/meilisearch/meilisearch/pull/2948/files#diff-21e50aae04d9a49b84a561124faf0389e9fa35d0d366f8616c95def5298faebfR10) even though I want to use just Code and ErrorCode.

I would really appreciate your review and help 🙏

**Comment by curquiza** [comment]
Maybe @ManyTheFish can help you on this? 😊

**Comment by ManyTheFish** [comment]
Hello @shogohida, it seems that the message actually generated comes from https://github.com/meilisearch/meilisearch/blob/fcedce8578ca9dfa5366485b4eb87070199821c4/meilisearch-http/src/task.rs#L49-L52, you should probably start your investigation from here.

**Comment by shogohida** [comment]
@ManyTheFish 
Thanks for your comment! 

Well, I knew the message comes from the point you mentioned. I already changed the message for invalid_task_status.

https://github.com/meilisearch/meilisearch/pull/2948/files#diff-21e50aae04d9a49b84a561124faf0389e9fa35d0d366f8616c95def5298faebfR97-R98

I get the message like this and haven't been able to show "invalid_task_type" for "code" and "link"
スクリーンショット 2022-10-26 3 02 32

**Comment by ManyTheFish** [comment]
Hello @shogohida, I don't understand, why don't you modify the error at line 49 instead of the error at line 103?

**Comment by curquiza** [comment]
Closing this issue due to lack of answers. Plus, we decided to implement this on our side, to avoid losing more time. We need this fix for v0.30.0.

Thanks anyway for your work! 😄

**Comment by shogohida** [comment]
@curquiza 
I'm so sorry for not responding 🙇 I couldn't implement this myself so I will see your implementation to see how close my implementation was and which parts were wrong.

Thanks for your message! Hope to contribute to another issue in the future 👍

**Comment by curquiza** [comment]
No problem @shogohida, you made your best, and we found out the issue was not that easy! It's completely normal you don't have the time for this, don't worry. Of course you are more than welcome to come back contributing 😄

**Comment by shogohida** [comment]
Merci! I look forward to seeing the correct code!

**Pull request closed without merging**
