### PR TITLE
Add test search

### PR DESCRIPTION
**Pull request by LegendreM**
- Get an error if the index does not exist
- Get an error if a parameter is not expected (e.g.: "lol")
- Check a basic search with no parameter
- Check a basic search with only a q parameter

isssue #814

### CODE REVIEW

**Comment by LegendreM** [comment]
bors try

**Review by Kerollmops — APPROVED** [review]
Nice work, thank you for your contribution :)

Is it the #Hacktoberfest that make you discover meilisearch?

**Comment by LegendreM** [comment]
Hey @Kerollmops @MarinPostma can we merge this ?

**Comment by LegendreM** [comment]
bors try

**Review by Kerollmops — APPROVED** [review]

**Comment by LegendreM** [comment]
bors merge

**Pull request merged**
