### PR TITLE
Fix deletion bug that sometimes occur when using `disableOnAttributes` typo setting

### PR DESCRIPTION
**Pull request by loiclec**
Fixes https://github.com/meilisearch/meilisearch/issues/3816

The idea of the fix is simple: we keep not only a list of words to delete, but also a list of words to **keep**, which takes precedence.
To get the final, correct list of words to delete from the FST, we look at those that should both be deleted and not kept.

### CODE REVIEW

**Review by Kerollmops — DISMISSED** [review]
Wow! Thank you very much @loiclec 🤩
Thank you for the test too!
bors merge

**Comment by loiclec** [comment]
Oh? 🤔  I saw the same test failures in my tests, but I thought I fixed them already. Sorry about that, will double-check my work!

**Comment by loiclec** [comment]
Should be fixed now! :) let's wait for the full test results!
I initialised the `must_keep` variable to `true`, but it should have been initialised to `false`.

**Review by curquiza — CHANGES_REQUESTED** [review]
Please don't merge this PR without discussing with @gillian-meilisearch. Plus it's not [the process we do usually](https://github.com/meilisearch/engine-team/blob/main/resources/meilisearch-release.md#how-to-do-patched-release-following-hotfixes)
No new branches have been created for the patch + no milestones.
I remind v1.2 has already been released

**Comment by loiclec** [comment]
Closed. The fix will be in v1.3 but not in a patch release of v1.2

**Pull request closed without merging**
