### PR TITLE
Update dependencies for v1.4

### LINKED ISSUE #3870: Upgrade dependencies
This issue is about updating Meilisearch dependencies:
  - [x] Cargo toml dependencies of Meilisearch; but also the main engine-team repositories that Meilisearch depends on (charabia, heed...)
  - [ ] If new Rust versions have been released, update the Rust version in the Clippy job of this [GitHub Action file](https://github.com/meilisearch/meilisearch/blob/main/.github/workflows/test-suite.yml)

⚠️ To avoid last minute bugs, this issue should only be done at the beginning of the sprint!

The GitHub action dependencies are managed by [Dependabot](https://github.com/meilisearch/meilisearch/blob/main/.github/dependabot.yml), so no need to update them when solving this issue.

### PR DESCRIPTION
**Pull request by ManyTheFish**
# Pull Request

## Related issue
Fixes #3870 

## What does this PR do?
- [Update dependencies](https://github.com/meilisearch/meilisearch/pull/3987/commits/d7ff5368b4e300e1aaa702a769c4cfcccd277265)
- [upgrade itertools = "0.10.5"](https://github.com/meilisearch/meilisearch/pull/3987/commits/d0582d01f4f3400fa3b47ab4b1421b6c5fb347d5)
- [upgrade sysinfo = "0.29.7"](https://github.com/meilisearch/meilisearch/pull/3987/commits/507c66135264c9a2db98eebf5045840b8db29a27)
- [upgrade memmap2 = "0.7.1"](https://github.com/meilisearch/meilisearch/pull/3987/commits/489e0d5cd04bb1bf131107da0cd18e8be482eed5)
- [upgrade rstar = "0.11.0"](https://github.com/meilisearch/meilisearch/pull/3987/commits/3d9d08e3b253f1fd158352721642a33771e4bd24)
- [upgrade fastrand = "2.0.0"](https://github.com/meilisearch/meilisearch/pull/3987/commits/1af7083c48b7e7d0980aa62144e60b8724246c72)
- [upgrade deserr = "0.6.0"](https://github.com/meilisearch/meilisearch/pull/3987/commits/7fe77045af3cee42d6d8f8dccc2f00bd069bb42e)
- [upgrade indexmap = "2.0.0"](https://github.com/meilisearch/meilisearch/pull/3987/commits/95e4960b0cf9cca152010d82f390e76dd5203028)
- [update rust toolchain = "1.71.1"](https://github.com/meilisearch/meilisearch/pull/3987/commits/937b7b5da559e859354d1af52b2bfe20fe80ef76)

## Remaining un-upgraded dependencies
- vergen 7.5.1 --> 8.2.4: I wasn't able to quickly understand the changes in the lib API to upgrade the dependency
- rustls 0.20.8 --> 0.21.6: Meilisearch doesn't have any direct dependency on it

### CODE REVIEW

**Review by curquiza — CHANGES_REQUESTED** [review]
In the issue there is: 

> If new Rust versions have been released, update the Rust version in the Clippy job of this [GitHub Action file](https://github.com/meilisearch/meilisearch/blob/main/.github/workflows/test-suite.yml)

@ManyTheFish can you update the Rust version too please? 😊

**Review by curquiza — CHANGES_REQUESTED** [review]
I think the Clippy CI is red now

https://github.com/meilisearch/meilisearch/actions/runs/5819047355/job/15776685156?pr=3987

**Review by irevoire — APPROVED** [review]
bors merge

**Review by curquiza — APPROVED** [review]
bors merge

**Comment by curquiza** [comment]
bors merge

**Comment by curquiza** [comment]
bors merge-

**Pull request merged**
