### PR TITLE
Fix import of dump v2

### LINKED ISSUE #3435: Importing a dump from v0.22 doesn't work on v1.0.0-rc.2
I tried to import this dump, and Meillisearch wasn't able to import it.
[20230130-162609246.tar.gz](https://github.com/meilisearch/meilisearch/files/10537721/20230130-162609246.tar.gz)

### PR DESCRIPTION
**Pull request by irevoire**
# Pull Request
This bug was introduced because of a mistake we did earlier: We said the last version to export dump v2 was the v0.21.0 while it was the v0.22.0.
To fix the bug I updated our whole v2 reader to use the code from meilisearch v0.22.0.
Also:
- Import the bugged dump in the tests
- Test the import of this dump in the v2 reader and current reader

## Related issue
Fixes #3435

### CODE REVIEW

**Review by dureuill — APPROVED** [review]
Thank you for your work! The code looks good to me, I didn't test but from the tests you reported in the PR description and the ones you added I think we have sufficient coverage.

bors merge

**Comment by Kerollmops** [comment]
Have we updated the documentation about the dumps and compatibility?

**Comment by irevoire** [comment]
I updated the spec iirc but I don't know for the doc

**Comment by dureuill** [comment]
AFAIK there has been https://github.com/meilisearch/documentation/pull/2102 on the docs side

**Comment by curquiza** [comment]
@Kerollmops if you want to ensure the docs is updating correctly
- you can check our issues on Meilisearch repo, you will find [this one](https://github.com/meilisearch/meilisearch/issues/2985) 😊 
- as Louis mentioned, you can check the issue on the docs side or the central PR [here](https://github.com/meilisearch/documentation/pull/2098)

**Pull request merged**
