### PR TITLE
Clarify error message when the db and engine versions are incompatible

### PR DESCRIPTION
**Pull request by dureuill**
# Pull Request

## Related issue

Related to https://github.com/meilisearch/meilisearch/issues/2752

## What does this PR do?
- Implements https://github.com/meilisearch/product/discussions/572#discussioncomment-4390616

## PR checklist
Please check if your PR fulfills the following requirements:
- [ ] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Review by loiclec — APPROVED** [review]
Thanks Louis :)

**Comment by loiclec** [comment]
bors merge

**Comment by irevoire** [comment]
IS THIS A FLAKY TEST?

bors merge

**Comment by curquiza** [comment]
I think the issue we want to link here is: https://github.com/meilisearch/meilisearch/issues/3250 😇

**Pull request merged**
