### PR TITLE
feat(kubernetes): add initial manifests

### PR DESCRIPTION
**Pull request by Rio**
This is for a very basic deployment. Environment variables are pulled in from a configmap but are optional.
MEILI_MASTER_KEY currently is pulled from a secret.

An example with kustomize for changing some of these values is included.

### CODE REVIEW

**Comment by Kerollmops** [comment]
He @Rio,

Thank you very much for your PR, I am currently talking with the documentation team because I think that it would be better to put this _tutorial_ in the documentation itself. Would be easier to find it in part using the search engine itself which scrapped put documentation pages.

**Comment by Rio** [comment]
Hey @Kerollmops,

I have to admit it was more of a quick brain dump than anything else.
At first I'd thought I'd just put the manifests there but then remembered that some quick docs could help.
Didn't look at where to put it though, sorry about that.

**Comment by Kerollmops** [comment]
No worries, this is real kind to you to share your knwoledge. I will reached when we reached a decision with the documentation team eventually. Thank you for your work 😃

**Comment by tpayet** [comment]
Hi @Rio, thank you so much for sharing this
 As @Kerollmops said, this repository might not be the best place for this content but we would be very interested in having this tutorial in our documentation 😁 and have those kubernetes manifests in their own repository so we could have also an Helm chart from this repository. What do you think?

**Comment by Rio** [comment]
Yes that sounds nice. We store all our deployment manifests in a separate repo as wel. As long as a helm chart is not the only option ;) There is tremendous power in just being able to apply a directory with some minor changes. I have seen projects that render out their manifests from a helm chart and commit them to the repo to. This enables both helm style workflows as well as basic `kubectl apply -f ./` workflows.

**Comment by tpayet** [comment]
Yes of course, that makes total sense. Would you want to create the repo so we transfer its ownership to meilisearch org afterward or do you want me to create a repo in the org where I can set you maitainer?

**Comment by Rio** [comment]
If you could create it that would be grand. I'll see If I can find some time today to move some manifests over there.

**Comment by tpayet** [comment]
Great, I just invited you to this the [MeiliSearch-kubernetes](https://github.com/meilisearch/meilisearch-kubernetes) repo. You should be able to put your manifests there :) and we can evolve from there! Thanks again!

**Comment by Rio** [comment]
No problem!

**Pull request closed without merging**
