### PR TITLE
Force japanese v1.1.0

### PR DESCRIPTION
**Pull request by ManyTheFish**
# Pull Request
> ⚠️ this PR is not meant to be merged.

This PR deactivates Chinese tokenization forcing Japanese tokenization to be used by Meilisearch.
It's a hotfix provided to Japanese users allowing them to use Meilisearch without having language detection issues before a final fix is released.

### Docker images
**[Meilisearch v1.1.1](https://github.com/meilisearch/meilisearch/releases/tag/v1.1.1)** (latest):
```bash
$ docker pull getmeili/meilisearch:prototype-japanese-2
```

**[Meilisearch v1.1.0-rc.3](https://github.com/meilisearch/meilisearch/releases/tag/v1.1.0-rc.3)**:
```bash
$ docker pull getmeili/meilisearch:prototype-japanese-1
```

**[Meilisearch v1.1.0-rc.1](https://github.com/meilisearch/meilisearch/releases/tag/v1.1.0-rc.1)**:
```bash
$ docker pull getmeili/meilisearch:prototype-japanese-0
```

## Related issues and discussions

- https://github.com/meilisearch/product/discussions/532#discussioncomment-3806543
- https://github.com/meilisearch/meilisearch/issues/3565
- https://github.com/meilisearch/meilisearch/pull/3569

### CODE REVIEW

**Comment by miiton** [comment]
@ManyTheFish 

It seems that a panic occurs when trying to index documents containing "ッー". This issue has occurred in both `prototype-japanese-0` and `prototype-japanese-1`. Since it did not happen in `v1.0.2` and `v1.1.1`, I decided to write about it here.

image

panic message
```
thread 'indexing-thread:1' panicked at 'could not find kana 'っ' in TO_ROMAJI map', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/wana_kana-2.1.2/src/utils/katakana_to_hiragana.rs:62:36
```

Related: https://github.com/PSeitz/wana_kana_rust/issues/13 (Reported by @kounoike)

**Comment by ManyTheFish** [comment]
@miiton, Thank you for your report, I'll fix it ASAP!

**Comment by ManyTheFish** [comment]
Hello @miiton, A new prototype up-to-date with v1.1.1 has been released hot fixing the issue you pointed out before:
- prototype-japanese-2

I updated the PR description in consequence.

**Comment by miiton** [comment]
I thought it was a nice feature to be able to search for katakana words in hiragana (and vice versa), but this fix has disabled that once and for all, correct?
Is [this change](https://github.com/meilisearch/meilisearch/pull/3588/commits/0fbda6383b13170ce04c1bd002c643812d32bb22) planned to be reverted once [wana_kana](https://github.com/PSeitz/wana_kana_rust/issues/13) is fixed?

**prototype-japanese-1**
```bash
curl ... -X POST localhost:7700/indexes/hogehoge/documents -d '{"id":1,"name":"パイナップル"}'
# {"taskUid":0,"indexUid":"hogehoge","status":"enqueued","type":"documentAdditionOrUpdate","enqueuedAt":"2023-05-04T23:28:15.037778125Z"}

curl ... -X POST localhost:7700/indexes/hogehoge/search -d '{"q":"パイナップル"}'
# {"hits":[{"id":1,"name":"パイナップル"}],"query":"パイナップル","processingTimeMs":2,"limit":20,"offset":0,"estimatedTotalHits":1}

curl ... -X POST localhost:7700/indexes/hogehoge/search -d '{"q":"ぱいなっぷる"}'
# {"hits":[{"id":1,"name":"パイナップル"}],"query":"ぱいなっぷる","processingTimeMs":0,"limit":20,"offset":0,"estimatedTotalHits":1} -- hit
```


**prototype-japanese-2**
```bash
curl ... -X POST localhost:7700/indexes/hogehoge/documents -d '{"id":1,"name":"パイナップル"}'
# {"taskUid":0,"indexUid":"hogehoge","status":"enqueued","type":"documentAdditionOrUpdate","enqueuedAt":"2023-05-04T23:28:15.037778125Z"}

curl ... -X POST localhost:7700/indexes/hogehoge/search -d '{"q":"ぱいなっぷる"}'
# {"hits":[],"query":"ぱいなっぷる","processingTimeMs":0,"limit":20,"offset":0,"estimatedTotalHits":0}  -- not hit
```

**Comment by ManyTheFish** [comment]
Hello @miiton,
I'm pleased that you liked the Kana conversion tried in this prototype, and yes, if you feel that it's a good feature for the Japanese Language support, then I will reintegrate it after the fix!
Moreover, when we find a convenient way to handle Kanji texts properly, we could integrate this feature in the official Meilisearch versions.

**Pull request closed without merging**
