### PR TITLE
Fix a bug where the filestore could try to parse its own tmp file and fail

### LINKED ISSUE #3502: /stats endpoint internal server error
**Describe the bug**
Hitting the stats endpoint on our Meilsearch index reliably produces an HTTP 500 error and an internal error message:

```
curl -v -H "Authorization: Bearer $(chamberprod read -q meilisearch meili_master_key)" 10.8.78.128:7700/stats | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 10.8.78.128:7700...
* Connected to 10.8.78.128 (10.8.78.128) port 7700 (#0)
> GET /stats HTTP/1.1
> Host: 10.8.78.128:7700
> User-Agent: curl/7.85.0
> Accept: */*
> Authorization: Bearer parq78bdx3bwbh4jadqogchetphh3jr3
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< content-length: 205
< vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
< content-type: application/json
< date: Thu, 16 Feb 2023 03:06:46 GMT
<
{ [205 bytes data]
100   205  100   205    0     0   4577      0 --:--:-- --:--:-- --:--:--  5000
* Connection #0 to host 10.8.78.128 left intact
{
  "message": "invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-zA-Z], found `.` at 1",
  "code": "internal",
  "type": "internal",
  "link": "https://docs.meilisearch.com/errors#internal"
}
```

The logs from the server added no additional info; it would be nice to see a full stacktrace there when errors are encountered.

We have only one index, and can read stats for it without issue, so I'm guessing that the problem is in the global stats somewhere:

```
$ curl -H "Authorization: Bearer $(chamberprod read -q meilisearch meili_master_key)" 10.8.78.128:7700/indexes | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   177  100   177    0     0   3862      0 --:--:-- --:--:-- --:--:--  4214
{
  "results": [
    {
      "uid": "compilation",
      "createdAt": "2023-02-09T11:21:50.224338487Z",
      "updatedAt": "2023-02-16T02:58:59.745210844Z",
      "primaryKey": "uuid"
    }
  ],
  "offset": 0,
  "limit": 20,
  "total": 1
}
$ curl -H "Authorization: Bearer $(chamberprod read -q meilisearch meili_master_key)" 10.8.78.128:7700/indexes/compilation/stats | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   363  100   363    0     0   7993      0 --:--:-- --:--:-- --:--:--  8642
{
  "numberOfDocuments": 90348,
  "isIndexing": true,
  "fieldDistribution": {
    "activities": 63389,
    "description": 90348,
    "library_uuids": 90348,
    "publisher_uuid": 90348,
    "release_note": 90348,
    "serial_number": 90348,
    "student_facing_description": 90348,
    "subtitle": 90348,
    "teacher_note": 90348,
    "title": 90348,
    "topic_descriptions": 90348,
    "topics": 90348,
    "uuid": 90348,
    "version_created_on": 90348
  }
}
```

**To Reproduce**
Hit the `/stats` endpoint.

I've only got one server to test this on right now, but I'm planning on cycling to a new one in a few days, so I'll update with whether the error persists.

**Expected behavior**
I expected the stats to be returned with no error.

**Meilisearch version:**
1.0.0

**Additional context**
We're running Meilisearch on an AWS `m6i.2xlarge` instance with 8 vCPU and 32GB of memory with about 43GB of data in the one index.

### PR DESCRIPTION
**Pull request by irevoire**
Fixes  #3502

The bug is that, while receiving an update, the file store create a temporary file named something like `.tmpX123Y456Z`.
And then, when asking for the list of uuids available in the task store, we were trying to parse this kind of filename as an `uuidv4` instead of ignoring them.

This bug has been introduced in the v1.0 of meilisearch and only affects the global stats route.

### CODE REVIEW

**Comment by curquiza** [comment]
If for v1.0.2, should be put into `release-v1.0.2` branch. Otherwise, if for v1.1.0, `main` is perfect

**Review by dureuill — APPROVED** [review]
This fixes the issue, however I wonder if we should maybe be even more lenient on what happens if we can't parse a filename as a UUID, since these are the only files we're interested in for the purpose of computing the size. What do you think?

**Comment by dureuill** [comment]
I agree with the rule you quoted, but in the context of walking a directory I can't prevent myself from feeling like we are inherently "accepting things from others".

However, we already had this discussion in the previous PR, so no need to relitigate it here. Your point that we control the `data.ms` directory is valid.

I approved, feel free to merge 👍

**Comment by irevoire** [comment]
bors merge

**Review by dureuill — APPROVED** [review]

**Comment by irevoire** [comment]
bors merge

**Pull request merged**
