### PR TITLE
Fix score details casing

### LINKED ISSUE #3941: Attribute casing in score details is snake_case instead of expected camelCase
When using the score details feature the attributes properties don't use camelCase like the other properties do.
```
 "attribute": {
    "order": 3,
     "attribute_ranking_order_score": 1.0,
     "query_word_distance_score": 0.8181818181818182,
     "score": 0.9090909090909091
  },
```
Noted [in the spec](https://github.com/meilisearch/specifications/pull/252/files#r1262783915 as well. Will need to be updated there and in the [blog post](https://blog.meilisearch.com/p/0f9e8a28-1657-4e00-b137-15ddfe6c7ba3/) for 1.3 as well if we correct this before the release.

Version: v1.3.-rc.0

(Louis messaged about this earlier and said that we'd need to change the implementation in score_details.rs & update the spec to match)

### PR DESCRIPTION
**Pull request by ManyTheFish**
# Pull Request

Fixes #3941

### CODE REVIEW

**Comment by Kerollmops** [comment]
bors try

**Review by Kerollmops — CHANGES_REQUESTED** [review]
Is it `attributeRankingOrderScore` or `attributeRankingOrder`?

**Comment by ManyTheFish** [comment]
Linking the final choice:
https://github.com/meilisearch/specifications/pull/252/files#r1273984997

**Review by Kerollmops — APPROVED** [review]
Looks good to me 🦪
bors merge

**Pull request merged**
